package net.ymate.module.wechat.model;

import net.ymate.platform.core.beans.annotation.PropertyState;
import net.ymate.platform.persistence.annotation.Default;
import net.ymate.platform.persistence.annotation.Entity;
import net.ymate.platform.persistence.annotation.Id;
import net.ymate.platform.persistence.annotation.Property;
import net.ymate.platform.persistence.jdbc.support.BaseEntity;

/**
 * WechatUser generated By EntityGenerator on 2016/07/05 上午 02:06:09
 *
 * @author YMP
 * @version 1.0
 */
@Entity("wechat_user")
public class WechatUser extends BaseEntity<WechatUser, String> {

    private static final long serialVersionUID = 1L;

    @Id
    @Property(name = "id", nullable = false, length = 32)
    @PropertyState(propertyName = "id")
    private String id;

    @Property(name = "open_id", nullable = false, length = 256)
    @PropertyState(propertyName = "open_id")
    private String openId;

    @Property(name = "union_id", length = 32)
    @PropertyState(propertyName = "union_id")
    private String unionId;

    @Property(name = "nick_name", length = 32)
    @PropertyState(propertyName = "nick_name")
    private String nickName;

    @Property(name = "gender", unsigned = true, length = 1)
    @Default("0")
    @PropertyState(propertyName = "gender")
    private Integer gender;

    @Property(name = "head_img_url", length = 255)
    @PropertyState(propertyName = "head_img_url")
    private String headImgUrl;

    @Property(name = "signature", length = 100)
    @PropertyState(propertyName = "signature")
    private String signature;

    @Property(name = "country", length = 32)
    @PropertyState(propertyName = "country")
    private String country;

    @Property(name = "province", length = 32)
    @PropertyState(propertyName = "province")
    private String province;

    @Property(name = "city", length = 32)
    @PropertyState(propertyName = "city")
    private String city;

    @Property(name = "language", length = 10)
    @PropertyState(propertyName = "language")
    private String language;

    @Property(name = "is_subscribe", unsigned = true, length = 1)
    @Default("0")
    @PropertyState(propertyName = "is_subscribe")
    private Integer isSubscribe;

    @Property(name = "subscribe_time", nullable = false, length = 13)
    @PropertyState(propertyName = "subscribe_time")
    private Long subscribeTime;

    @Property(name = "unsubscribe_time", length = 13)
    @Default("0")
    @PropertyState(propertyName = "unsubscribe_time")
    private Long unsubscribeTime;

    @Property(name = "tag_id_list", length = 32)
    @PropertyState(propertyName = "tag_id_list")
    private String tagIdList;

    @Property(name = "account_id", nullable = false, length = 32)
    @PropertyState(propertyName = "account_id")
    private String accountId;

    @Property(name = "last_active_time", nullable = false, length = 13)
    @Default("0")
    @PropertyState(propertyName = "last_active_time")
    private Long lastActiveTime;

    @Property(name = "site_id", nullable = false, length = 32)
    @PropertyState(propertyName = "site_id")
    private String siteId;

    @Property(name = "status", unsigned = true, length = 2)
    @Default("0")
    @PropertyState(propertyName = "status")
    private Integer status;

    @Property(name = "remark", length = 100)
    @PropertyState(propertyName = "remark")
    private String remark;

    @Property(name = "oauth_access_token", length = 512)
    @PropertyState(propertyName = "oauth_access_token")
    private String oauthAccessToken;

    @Property(name = "oauth_refresh_token", length = 512)
    @PropertyState(propertyName = "oauth_refresh_token")
    private String oauthRefreshToken;

    @Property(name = "oauth_expired_time", length = 13)
    @Default("0")
    @PropertyState(propertyName = "oauth_expired_time")
    private Long oauthExpiredTime;

    @Property(name = "oauth_scope", length = 100)
    @PropertyState(propertyName = "oauth_scope")
    private String oauthScope;

    @Property(name = "last_modify_time", length = 13)
    @Default("0")
    @PropertyState(propertyName = "last_modify_time")
    private Long lastModifyTime;

    /**
     * 构造器
     */
    public WechatUser() {
    }

    /**
     * 构造器
     *
     * @param id
     * @param openId
     * @param subscribeTime
     * @param accountId
     * @param lastActiveTime
     * @param siteId
     */
    public WechatUser(String id, String openId, Long subscribeTime, String accountId, Long lastActiveTime, String siteId) {
        this.id = id;
        this.openId = openId;
        this.subscribeTime = subscribeTime;
        this.accountId = accountId;
        this.lastActiveTime = lastActiveTime;
        this.siteId = siteId;
    }

    /**
     * 构造器
     *
     * @param id
     * @param openId
     * @param unionId
     * @param nickName
     * @param gender
     * @param headImgUrl
     * @param signature
     * @param country
     * @param province
     * @param city
     * @param language
     * @param isSubscribe
     * @param subscribeTime
     * @param unsubscribeTime
     * @param tagIdList
     * @param accountId
     * @param lastActiveTime
     * @param siteId
     * @param status
     * @param remark
     * @param oauthAccessToken
     * @param oauthRefreshToken
     * @param oauthExpiredTime
     * @param oauthScope
     * @param lastModifyTime
     */
    public WechatUser(String id, String openId, String unionId, String nickName, Integer gender, String headImgUrl, String signature, String country, String province, String city, String language, Integer isSubscribe, Long subscribeTime, Long unsubscribeTime, String tagIdList, String accountId, Long lastActiveTime, String siteId, Integer status, String remark, String oauthAccessToken, String oauthRefreshToken, Long oauthExpiredTime, String oauthScope, Long lastModifyTime) {
        this.id = id;
        this.openId = openId;
        this.unionId = unionId;
        this.nickName = nickName;
        this.gender = gender;
        this.headImgUrl = headImgUrl;
        this.signature = signature;
        this.country = country;
        this.province = province;
        this.city = city;
        this.language = language;
        this.isSubscribe = isSubscribe;
        this.subscribeTime = subscribeTime;
        this.unsubscribeTime = unsubscribeTime;
        this.tagIdList = tagIdList;
        this.accountId = accountId;
        this.lastActiveTime = lastActiveTime;
        this.siteId = siteId;
        this.status = status;
        this.remark = remark;
        this.oauthAccessToken = oauthAccessToken;
        this.oauthRefreshToken = oauthRefreshToken;
        this.oauthExpiredTime = oauthExpiredTime;
        this.oauthScope = oauthScope;
        this.lastModifyTime = lastModifyTime;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }


    /**
     * @return the openId
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * @param openId the openId to set
     */
    public void setOpenId(String openId) {
        this.openId = openId;
    }

    /**
     * @return the unionId
     */
    public String getUnionId() {
        return unionId;
    }

    /**
     * @param unionId the unionId to set
     */
    public void setUnionId(String unionId) {
        this.unionId = unionId;
    }

    /**
     * @return the nickName
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * @param nickName the nickName to set
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * @return the gender
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * @param gender the gender to set
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * @return the headImgUrl
     */
    public String getHeadImgUrl() {
        return headImgUrl;
    }

    /**
     * @param headImgUrl the headImgUrl to set
     */
    public void setHeadImgUrl(String headImgUrl) {
        this.headImgUrl = headImgUrl;
    }

    /**
     * @return the signature
     */
    public String getSignature() {
        return signature;
    }

    /**
     * @param signature the signature to set
     */
    public void setSignature(String signature) {
        this.signature = signature;
    }

    /**
     * @return the country
     */
    public String getCountry() {
        return country;
    }

    /**
     * @param country the country to set
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * @return the province
     */
    public String getProvince() {
        return province;
    }

    /**
     * @param province the province to set
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * @return the city
     */
    public String getCity() {
        return city;
    }

    /**
     * @param city the city to set
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * @return the language
     */
    public String getLanguage() {
        return language;
    }

    /**
     * @param language the language to set
     */
    public void setLanguage(String language) {
        this.language = language;
    }

    /**
     * @return the isSubscribe
     */
    public Integer getIsSubscribe() {
        return isSubscribe;
    }

    /**
     * @param isSubscribe the isSubscribe to set
     */
    public void setIsSubscribe(Integer isSubscribe) {
        this.isSubscribe = isSubscribe;
    }

    /**
     * @return the subscribeTime
     */
    public Long getSubscribeTime() {
        return subscribeTime;
    }

    /**
     * @param subscribeTime the subscribeTime to set
     */
    public void setSubscribeTime(Long subscribeTime) {
        this.subscribeTime = subscribeTime;
    }

    /**
     * @return the unsubscribeTime
     */
    public Long getUnsubscribeTime() {
        return unsubscribeTime;
    }

    /**
     * @param unsubscribeTime the unsubscribeTime to set
     */
    public void setUnsubscribeTime(Long unsubscribeTime) {
        this.unsubscribeTime = unsubscribeTime;
    }

    /**
     * @return the tagIdList
     */
    public String getTagIdList() {
        return tagIdList;
    }

    /**
     * @param tagIdList the tagIdList to set
     */
    public void setTagIdList(String tagIdList) {
        this.tagIdList = tagIdList;
    }

    /**
     * @return the accountId
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * @param accountId the accountId to set
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    /**
     * @return the lastActiveTime
     */
    public Long getLastActiveTime() {
        return lastActiveTime;
    }

    /**
     * @param lastActiveTime the lastActiveTime to set
     */
    public void setLastActiveTime(Long lastActiveTime) {
        this.lastActiveTime = lastActiveTime;
    }

    /**
     * @return the siteId
     */
    public String getSiteId() {
        return siteId;
    }

    /**
     * @param siteId the siteId to set
     */
    public void setSiteId(String siteId) {
        this.siteId = siteId;
    }

    /**
     * @return the status
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * @param status the status to set
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * @return the remark
     */
    public String getRemark() {
        return remark;
    }

    /**
     * @param remark the remark to set
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * @return the oauthAccessToken
     */
    public String getOauthAccessToken() {
        return oauthAccessToken;
    }

    /**
     * @param oauthAccessToken the oauthAccessToken to set
     */
    public void setOauthAccessToken(String oauthAccessToken) {
        this.oauthAccessToken = oauthAccessToken;
    }

    /**
     * @return the oauthRefreshToken
     */
    public String getOauthRefreshToken() {
        return oauthRefreshToken;
    }

    /**
     * @param oauthRefreshToken the oauthRefreshToken to set
     */
    public void setOauthRefreshToken(String oauthRefreshToken) {
        this.oauthRefreshToken = oauthRefreshToken;
    }

    /**
     * @return the oauthExpiredTime
     */
    public Long getOauthExpiredTime() {
        return oauthExpiredTime;
    }

    /**
     * @param oauthExpiredTime the oauthExpiredTime to set
     */
    public void setOauthExpiredTime(Long oauthExpiredTime) {
        this.oauthExpiredTime = oauthExpiredTime;
    }

    /**
     * @return the oauthScope
     */
    public String getOauthScope() {
        return oauthScope;
    }

    /**
     * @param oauthScope the oauthScope to set
     */
    public void setOauthScope(String oauthScope) {
        this.oauthScope = oauthScope;
    }

    /**
     * @return the lastModifyTime
     */
    public Long getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * @param lastModifyTime the lastModifyTime to set
     */
    public void setLastModifyTime(Long lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }


    //
    // Chain
    //

    public static WechatUserBuilder builder() {
        return new WechatUserBuilder();
    }

    public WechatUserBuilder bind() {
        return new WechatUserBuilder(this);
    }

    public static class WechatUserBuilder {

        private WechatUser _model;

        public WechatUserBuilder() {
            _model = new WechatUser();
        }

        public WechatUserBuilder(WechatUser model) {
            _model = model;
        }

        public WechatUser build() {
            return _model;
        }

        public String id() {
            return _model.getId();
        }

        public WechatUserBuilder id(String id) {
            _model.setId(id);
            return this;
        }

        public String openId() {
            return _model.getOpenId();
        }

        public WechatUserBuilder openId(String openId) {
            _model.setOpenId(openId);
            return this;
        }

        public String unionId() {
            return _model.getUnionId();
        }

        public WechatUserBuilder unionId(String unionId) {
            _model.setUnionId(unionId);
            return this;
        }

        public String nickName() {
            return _model.getNickName();
        }

        public WechatUserBuilder nickName(String nickName) {
            _model.setNickName(nickName);
            return this;
        }

        public Integer gender() {
            return _model.getGender();
        }

        public WechatUserBuilder gender(Integer gender) {
            _model.setGender(gender);
            return this;
        }

        public String headImgUrl() {
            return _model.getHeadImgUrl();
        }

        public WechatUserBuilder headImgUrl(String headImgUrl) {
            _model.setHeadImgUrl(headImgUrl);
            return this;
        }

        public String signature() {
            return _model.getSignature();
        }

        public WechatUserBuilder signature(String signature) {
            _model.setSignature(signature);
            return this;
        }

        public String country() {
            return _model.getCountry();
        }

        public WechatUserBuilder country(String country) {
            _model.setCountry(country);
            return this;
        }

        public String province() {
            return _model.getProvince();
        }

        public WechatUserBuilder province(String province) {
            _model.setProvince(province);
            return this;
        }

        public String city() {
            return _model.getCity();
        }

        public WechatUserBuilder city(String city) {
            _model.setCity(city);
            return this;
        }

        public String language() {
            return _model.getLanguage();
        }

        public WechatUserBuilder language(String language) {
            _model.setLanguage(language);
            return this;
        }

        public Integer isSubscribe() {
            return _model.getIsSubscribe();
        }

        public WechatUserBuilder isSubscribe(Integer isSubscribe) {
            _model.setIsSubscribe(isSubscribe);
            return this;
        }

        public Long subscribeTime() {
            return _model.getSubscribeTime();
        }

        public WechatUserBuilder subscribeTime(Long subscribeTime) {
            _model.setSubscribeTime(subscribeTime);
            return this;
        }

        public Long unsubscribeTime() {
            return _model.getUnsubscribeTime();
        }

        public WechatUserBuilder unsubscribeTime(Long unsubscribeTime) {
            _model.setUnsubscribeTime(unsubscribeTime);
            return this;
        }

        public String tagIdList() {
            return _model.getTagIdList();
        }

        public WechatUserBuilder tagIdList(String tagIdList) {
            _model.setTagIdList(tagIdList);
            return this;
        }

        public String accountId() {
            return _model.getAccountId();
        }

        public WechatUserBuilder accountId(String accountId) {
            _model.setAccountId(accountId);
            return this;
        }

        public Long lastActiveTime() {
            return _model.getLastActiveTime();
        }

        public WechatUserBuilder lastActiveTime(Long lastActiveTime) {
            _model.setLastActiveTime(lastActiveTime);
            return this;
        }

        public String siteId() {
            return _model.getSiteId();
        }

        public WechatUserBuilder siteId(String siteId) {
            _model.setSiteId(siteId);
            return this;
        }

        public Integer status() {
            return _model.getStatus();
        }

        public WechatUserBuilder status(Integer status) {
            _model.setStatus(status);
            return this;
        }

        public String remark() {
            return _model.getRemark();
        }

        public WechatUserBuilder remark(String remark) {
            _model.setRemark(remark);
            return this;
        }

        public String oauthAccessToken() {
            return _model.getOauthAccessToken();
        }

        public WechatUserBuilder oauthAccessToken(String oauthAccessToken) {
            _model.setOauthAccessToken(oauthAccessToken);
            return this;
        }

        public String oauthRefreshToken() {
            return _model.getOauthRefreshToken();
        }

        public WechatUserBuilder oauthRefreshToken(String oauthRefreshToken) {
            _model.setOauthRefreshToken(oauthRefreshToken);
            return this;
        }

        public Long oauthExpiredTime() {
            return _model.getOauthExpiredTime();
        }

        public WechatUserBuilder oauthExpiredTime(Long oauthExpiredTime) {
            _model.setOauthExpiredTime(oauthExpiredTime);
            return this;
        }

        public String oauthScope() {
            return _model.getOauthScope();
        }

        public WechatUserBuilder oauthScope(String oauthScope) {
            _model.setOauthScope(oauthScope);
            return this;
        }

        public Long lastModifyTime() {
            return _model.getLastModifyTime();
        }

        public WechatUserBuilder lastModifyTime(Long lastModifyTime) {
            _model.setLastModifyTime(lastModifyTime);
            return this;
        }

    }

    /**
     * WechatUser 字段常量表
     */
    public class FIELDS {
        public static final String ID = "id";
        public static final String OPEN_ID = "open_id";
        public static final String UNION_ID = "union_id";
        public static final String NICK_NAME = "nick_name";
        public static final String GENDER = "gender";
        public static final String HEAD_IMG_URL = "head_img_url";
        public static final String SIGNATURE = "signature";
        public static final String COUNTRY = "country";
        public static final String PROVINCE = "province";
        public static final String CITY = "city";
        public static final String LANGUAGE = "language";
        public static final String IS_SUBSCRIBE = "is_subscribe";
        public static final String SUBSCRIBE_TIME = "subscribe_time";
        public static final String UNSUBSCRIBE_TIME = "unsubscribe_time";
        public static final String TAG_ID_LIST = "tag_id_list";
        public static final String ACCOUNT_ID = "account_id";
        public static final String LAST_ACTIVE_TIME = "last_active_time";
        public static final String SITE_ID = "site_id";
        public static final String STATUS = "status";
        public static final String REMARK = "remark";
        public static final String OAUTH_ACCESS_TOKEN = "oauth_access_token";
        public static final String OAUTH_REFRESH_TOKEN = "oauth_refresh_token";
        public static final String OAUTH_EXPIRED_TIME = "oauth_expired_time";
        public static final String OAUTH_SCOPE = "oauth_scope";
        public static final String LAST_MODIFY_TIME = "last_modify_time";
    }

    public static final String TABLE_NAME = "wechat_user";

}
