package net.ymate.module.wechat.model;

import net.ymate.platform.core.beans.annotation.PropertyState;
import net.ymate.platform.persistence.annotation.Default;
import net.ymate.platform.persistence.annotation.Entity;
import net.ymate.platform.persistence.annotation.Id;
import net.ymate.platform.persistence.annotation.Property;
import net.ymate.platform.persistence.jdbc.support.BaseEntity;

/**
 * WechatAutoreply generated By EntityGenerator on 2016/07/11 上午 01:08:18
 *
 * @author YMP
 * @version 1.0
 */
@Entity("wechat_autoreply")
public class WechatAutoreply extends BaseEntity<WechatAutoreply, java.lang.String> {

    private static final long serialVersionUID = 1L;

    @Id
    @Property(name = "id", nullable = false, length = 32)
    @PropertyState(propertyName = "id")
    private java.lang.String id;

    @Property(name = "account_id", nullable = false, length = 32)
    @PropertyState(propertyName = "account_id")
    private java.lang.String accountId;

    @Property(name = "is_autoreply_open", unsigned = true, length = 1)
    @Default("1")
    @PropertyState(propertyName = "is_autoreply_open")
    private java.lang.Integer isAutoreplyOpen;

    @Property(name = "is_subscribe_reply_open", unsigned = true, length = 1)
    @Default("1")
    @PropertyState(propertyName = "is_subscribe_reply_open")
    private java.lang.Integer isSubscribeReplyOpen;

    @Property(name = "subscribe_autoreply_type", length = 10)
    @PropertyState(propertyName = "subscribe_autoreply_type")
    private java.lang.String subscribeAutoreplyType;

    @Property(name = "subscribe_autoreply_content", length = 32)
    @PropertyState(propertyName = "subscribe_autoreply_content")
    private java.lang.String subscribeAutoreplyContent;

    @Property(name = "default_autoreply_type", length = 10)
    @PropertyState(propertyName = "default_autoreply_type")
    private java.lang.String defaultAutoreplyType;

    @Property(name = "default_autoreply_content", length = 32)
    @PropertyState(propertyName = "default_autoreply_content")
    private java.lang.String defaultAutoreplyContent;

    @Property(name = "site_id", nullable = false, length = 32)
    @PropertyState(propertyName = "site_id")
    private java.lang.String siteId;

    @Property(name = "last_modify_time", length = 13)
    @Default("0")
    @PropertyState(propertyName = "last_modify_time")
    private java.lang.Long lastModifyTime;

    /**
     * 构造器
     */
    public WechatAutoreply() {
    }

    /**
     * 构造器
     *
     * @param id
     * @param accountId
     * @param siteId
     */
    public WechatAutoreply(java.lang.String id, java.lang.String accountId, java.lang.String siteId) {
        this.id = id;
        this.accountId = accountId;
        this.siteId = siteId;
    }

    /**
     * 构造器
     *
     * @param id
     * @param accountId
     * @param isAutoreplyOpen
     * @param isSubscribeReplyOpen
     * @param subscribeAutoreplyType
     * @param subscribeAutoreplyContent
     * @param defaultAutoreplyType
     * @param defaultAutoreplyContent
     * @param siteId
     * @param lastModifyTime
     */
    public WechatAutoreply(java.lang.String id, java.lang.String accountId, java.lang.Integer isAutoreplyOpen, java.lang.Integer isSubscribeReplyOpen, java.lang.String subscribeAutoreplyType, java.lang.String subscribeAutoreplyContent, java.lang.String defaultAutoreplyType, java.lang.String defaultAutoreplyContent, java.lang.String siteId, java.lang.Long lastModifyTime) {
        this.id = id;
        this.accountId = accountId;
        this.isAutoreplyOpen = isAutoreplyOpen;
        this.isSubscribeReplyOpen = isSubscribeReplyOpen;
        this.subscribeAutoreplyType = subscribeAutoreplyType;
        this.subscribeAutoreplyContent = subscribeAutoreplyContent;
        this.defaultAutoreplyType = defaultAutoreplyType;
        this.defaultAutoreplyContent = defaultAutoreplyContent;
        this.siteId = siteId;
        this.lastModifyTime = lastModifyTime;
    }

    public java.lang.String getId() {
        return id;
    }

    public void setId(java.lang.String id) {
        this.id = id;
    }


    /**
     * @return the accountId
     */
    public java.lang.String getAccountId() {
        return accountId;
    }

    /**
     * @param accountId the accountId to set
     */
    public void setAccountId(java.lang.String accountId) {
        this.accountId = accountId;
    }

    /**
     * @return the isAutoreplyOpen
     */
    public java.lang.Integer getIsAutoreplyOpen() {
        return isAutoreplyOpen;
    }

    /**
     * @param isAutoreplyOpen the isAutoreplyOpen to set
     */
    public void setIsAutoreplyOpen(java.lang.Integer isAutoreplyOpen) {
        this.isAutoreplyOpen = isAutoreplyOpen;
    }

    /**
     * @return the isSubscribeReplyOpen
     */
    public java.lang.Integer getIsSubscribeReplyOpen() {
        return isSubscribeReplyOpen;
    }

    /**
     * @param isSubscribeReplyOpen the isSubscribeReplyOpen to set
     */
    public void setIsSubscribeReplyOpen(java.lang.Integer isSubscribeReplyOpen) {
        this.isSubscribeReplyOpen = isSubscribeReplyOpen;
    }

    /**
     * @return the subscribeAutoreplyType
     */
    public java.lang.String getSubscribeAutoreplyType() {
        return subscribeAutoreplyType;
    }

    /**
     * @param subscribeAutoreplyType the subscribeAutoreplyType to set
     */
    public void setSubscribeAutoreplyType(java.lang.String subscribeAutoreplyType) {
        this.subscribeAutoreplyType = subscribeAutoreplyType;
    }

    /**
     * @return the subscribeAutoreplyContent
     */
    public java.lang.String getSubscribeAutoreplyContent() {
        return subscribeAutoreplyContent;
    }

    /**
     * @param subscribeAutoreplyContent the subscribeAutoreplyContent to set
     */
    public void setSubscribeAutoreplyContent(java.lang.String subscribeAutoreplyContent) {
        this.subscribeAutoreplyContent = subscribeAutoreplyContent;
    }

    /**
     * @return the defaultAutoreplyType
     */
    public java.lang.String getDefaultAutoreplyType() {
        return defaultAutoreplyType;
    }

    /**
     * @param defaultAutoreplyType the defaultAutoreplyType to set
     */
    public void setDefaultAutoreplyType(java.lang.String defaultAutoreplyType) {
        this.defaultAutoreplyType = defaultAutoreplyType;
    }

    /**
     * @return the defaultAutoreplyContent
     */
    public java.lang.String getDefaultAutoreplyContent() {
        return defaultAutoreplyContent;
    }

    /**
     * @param defaultAutoreplyContent the defaultAutoreplyContent to set
     */
    public void setDefaultAutoreplyContent(java.lang.String defaultAutoreplyContent) {
        this.defaultAutoreplyContent = defaultAutoreplyContent;
    }

    /**
     * @return the siteId
     */
    public java.lang.String getSiteId() {
        return siteId;
    }

    /**
     * @param siteId the siteId to set
     */
    public void setSiteId(java.lang.String siteId) {
        this.siteId = siteId;
    }

    /**
     * @return the lastModifyTime
     */
    public java.lang.Long getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * @param lastModifyTime the lastModifyTime to set
     */
    public void setLastModifyTime(java.lang.Long lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }


    //
    // Chain
    //

    public static WechatAutoreplyBuilder builder() {
        return new WechatAutoreplyBuilder();
    }

    public WechatAutoreplyBuilder bind() {
        return new WechatAutoreplyBuilder(this);
    }

    public static class WechatAutoreplyBuilder {

        private WechatAutoreply _model;

        public WechatAutoreplyBuilder() {
            _model = new WechatAutoreply();
        }

        public WechatAutoreplyBuilder(WechatAutoreply model) {
            _model = model;
        }

        public WechatAutoreply build() {
            return _model;
        }

        public java.lang.String id() {
            return _model.getId();
        }

        public WechatAutoreplyBuilder id(java.lang.String id) {
            _model.setId(id);
            return this;
        }

        public java.lang.String accountId() {
            return _model.getAccountId();
        }

        public WechatAutoreplyBuilder accountId(java.lang.String accountId) {
            _model.setAccountId(accountId);
            return this;
        }

        public java.lang.Integer isAutoreplyOpen() {
            return _model.getIsAutoreplyOpen();
        }

        public WechatAutoreplyBuilder isAutoreplyOpen(java.lang.Integer isAutoreplyOpen) {
            _model.setIsAutoreplyOpen(isAutoreplyOpen);
            return this;
        }

        public java.lang.Integer isSubscribeReplyOpen() {
            return _model.getIsSubscribeReplyOpen();
        }

        public WechatAutoreplyBuilder isSubscribeReplyOpen(java.lang.Integer isSubscribeReplyOpen) {
            _model.setIsSubscribeReplyOpen(isSubscribeReplyOpen);
            return this;
        }

        public java.lang.String subscribeAutoreplyType() {
            return _model.getSubscribeAutoreplyType();
        }

        public WechatAutoreplyBuilder subscribeAutoreplyType(java.lang.String subscribeAutoreplyType) {
            _model.setSubscribeAutoreplyType(subscribeAutoreplyType);
            return this;
        }

        public java.lang.String subscribeAutoreplyContent() {
            return _model.getSubscribeAutoreplyContent();
        }

        public WechatAutoreplyBuilder subscribeAutoreplyContent(java.lang.String subscribeAutoreplyContent) {
            _model.setSubscribeAutoreplyContent(subscribeAutoreplyContent);
            return this;
        }

        public java.lang.String defaultAutoreplyType() {
            return _model.getDefaultAutoreplyType();
        }

        public WechatAutoreplyBuilder defaultAutoreplyType(java.lang.String defaultAutoreplyType) {
            _model.setDefaultAutoreplyType(defaultAutoreplyType);
            return this;
        }

        public java.lang.String defaultAutoreplyContent() {
            return _model.getDefaultAutoreplyContent();
        }

        public WechatAutoreplyBuilder defaultAutoreplyContent(java.lang.String defaultAutoreplyContent) {
            _model.setDefaultAutoreplyContent(defaultAutoreplyContent);
            return this;
        }

        public java.lang.String siteId() {
            return _model.getSiteId();
        }

        public WechatAutoreplyBuilder siteId(java.lang.String siteId) {
            _model.setSiteId(siteId);
            return this;
        }

        public java.lang.Long lastModifyTime() {
            return _model.getLastModifyTime();
        }

        public WechatAutoreplyBuilder lastModifyTime(java.lang.Long lastModifyTime) {
            _model.setLastModifyTime(lastModifyTime);
            return this;
        }

    }

    /**
     * WechatAutoreply 字段常量表
     */
    public class FIELDS {
        public static final String ID = "id";
        public static final String ACCOUNT_ID = "account_id";
        public static final String IS_AUTOREPLY_OPEN = "is_autoreply_open";
        public static final String IS_SUBSCRIBE_REPLY_OPEN = "is_subscribe_reply_open";
        public static final String SUBSCRIBE_AUTOREPLY_TYPE = "subscribe_autoreply_type";
        public static final String SUBSCRIBE_AUTOREPLY_CONTENT = "subscribe_autoreply_content";
        public static final String DEFAULT_AUTOREPLY_TYPE = "default_autoreply_type";
        public static final String DEFAULT_AUTOREPLY_CONTENT = "default_autoreply_content";
        public static final String SITE_ID = "site_id";
        public static final String LAST_MODIFY_TIME = "last_modify_time";
    }

    public static final String TABLE_NAME = "wechat_autoreply";

}
