package net.ymate.module.wechat.model;

import net.ymate.platform.core.beans.annotation.PropertyState;
import net.ymate.platform.persistence.annotation.Default;
import net.ymate.platform.persistence.annotation.Entity;
import net.ymate.platform.persistence.annotation.Id;
import net.ymate.platform.persistence.annotation.Property;
import net.ymate.platform.persistence.jdbc.support.BaseEntity;

/**
 * WechatAutoreplyRule generated By EntityGenerator on 2016/07/11 上午 01:08:18
 *
 * @author YMP
 * @version 1.0
 */
@Entity("wechat_autoreply_rule")
public class WechatAutoreplyRule extends BaseEntity<WechatAutoreplyRule, String> {

    private static final long serialVersionUID = 1L;

    @Id
    @Property(name = "id", nullable = false, length = 32)
    @PropertyState(propertyName = "id")
    private String id;

    @Property(name = "account_id", nullable = false, length = 32)
    @PropertyState(propertyName = "account_id")
    private String accountId;

    @Property(name = "rule_name", nullable = false, length = 60)
    @PropertyState(propertyName = "rule_name")
    private String ruleName;

    @Property(name = "reply_mode", length = 10)
    @PropertyState(propertyName = "reply_mode")
    private String replyMode;

    @Property(name = "keyword_info", length = 16383)
    @PropertyState(propertyName = "keyword_info")
    private String keywordInfo;

    @Property(name = "reply_info", length = 16383)
    @PropertyState(propertyName = "reply_info")
    private String replyInfo;

    @Property(name = "site_id", nullable = false, length = 32)
    @PropertyState(propertyName = "site_id")
    private String siteId;

    @Property(name = "last_modify_time", length = 13)
    @Default("0")
    @PropertyState(propertyName = "last_modify_time")
    private Long lastModifyTime;

    /**
     * 构造器
     */
    public WechatAutoreplyRule() {
    }

    /**
     * 构造器
     *
     * @param id
     * @param accountId
     * @param ruleName
     * @param siteId
     */
    public WechatAutoreplyRule(String id, String accountId, String ruleName, String siteId) {
        this.id = id;
        this.accountId = accountId;
        this.ruleName = ruleName;
        this.siteId = siteId;
    }

    /**
     * 构造器
     *
     * @param id
     * @param accountId
     * @param ruleName
     * @param replyMode
     * @param keywordInfo
     * @param replyInfo
     * @param siteId
     * @param lastModifyTime
     */
    public WechatAutoreplyRule(String id, String accountId, String ruleName, String replyMode, String keywordInfo, String replyInfo, String siteId, Long lastModifyTime) {
        this.id = id;
        this.accountId = accountId;
        this.ruleName = ruleName;
        this.replyMode = replyMode;
        this.keywordInfo = keywordInfo;
        this.replyInfo = replyInfo;
        this.siteId = siteId;
        this.lastModifyTime = lastModifyTime;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }


    /**
     * @return the accountId
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * @param accountId the accountId to set
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    /**
     * @return the ruleName
     */
    public String getRuleName() {
        return ruleName;
    }

    /**
     * @param ruleName the ruleName to set
     */
    public void setRuleName(String ruleName) {
        this.ruleName = ruleName;
    }

    /**
     * @return the replyMode
     */
    public String getReplyMode() {
        return replyMode;
    }

    /**
     * @param replyMode the replyMode to set
     */
    public void setReplyMode(String replyMode) {
        this.replyMode = replyMode;
    }

    /**
     * @return the keywordInfo
     */
    public String getKeywordInfo() {
        return keywordInfo;
    }

    /**
     * @param keywordInfo the keywordInfo to set
     */
    public void setKeywordInfo(String keywordInfo) {
        this.keywordInfo = keywordInfo;
    }

    /**
     * @return the replyInfo
     */
    public String getReplyInfo() {
        return replyInfo;
    }

    /**
     * @param replyInfo the replyInfo to set
     */
    public void setReplyInfo(String replyInfo) {
        this.replyInfo = replyInfo;
    }

    /**
     * @return the siteId
     */
    public String getSiteId() {
        return siteId;
    }

    /**
     * @param siteId the siteId to set
     */
    public void setSiteId(String siteId) {
        this.siteId = siteId;
    }

    /**
     * @return the lastModifyTime
     */
    public Long getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * @param lastModifyTime the lastModifyTime to set
     */
    public void setLastModifyTime(Long lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }


    //
    // Chain
    //

    public static WechatAutoreplyRuleBuilder builder() {
        return new WechatAutoreplyRuleBuilder();
    }

    public WechatAutoreplyRuleBuilder bind() {
        return new WechatAutoreplyRuleBuilder(this);
    }

    public static class WechatAutoreplyRuleBuilder {

        private WechatAutoreplyRule _model;

        public WechatAutoreplyRuleBuilder() {
            _model = new WechatAutoreplyRule();
        }

        public WechatAutoreplyRuleBuilder(WechatAutoreplyRule model) {
            _model = model;
        }

        public WechatAutoreplyRule build() {
            return _model;
        }

        public String id() {
            return _model.getId();
        }

        public WechatAutoreplyRuleBuilder id(String id) {
            _model.setId(id);
            return this;
        }

        public String accountId() {
            return _model.getAccountId();
        }

        public WechatAutoreplyRuleBuilder accountId(String accountId) {
            _model.setAccountId(accountId);
            return this;
        }

        public String ruleName() {
            return _model.getRuleName();
        }

        public WechatAutoreplyRuleBuilder ruleName(String ruleName) {
            _model.setRuleName(ruleName);
            return this;
        }

        public String replyMode() {
            return _model.getReplyMode();
        }

        public WechatAutoreplyRuleBuilder replyMode(String replyMode) {
            _model.setReplyMode(replyMode);
            return this;
        }

        public String keywordInfo() {
            return _model.getKeywordInfo();
        }

        public WechatAutoreplyRuleBuilder keywordInfo(String keywordInfo) {
            _model.setKeywordInfo(keywordInfo);
            return this;
        }

        public String replyInfo() {
            return _model.getReplyInfo();
        }

        public WechatAutoreplyRuleBuilder replyInfo(String replyInfo) {
            _model.setReplyInfo(replyInfo);
            return this;
        }

        public String siteId() {
            return _model.getSiteId();
        }

        public WechatAutoreplyRuleBuilder siteId(String siteId) {
            _model.setSiteId(siteId);
            return this;
        }

        public Long lastModifyTime() {
            return _model.getLastModifyTime();
        }

        public WechatAutoreplyRuleBuilder lastModifyTime(Long lastModifyTime) {
            _model.setLastModifyTime(lastModifyTime);
            return this;
        }

    }

    /**
     * WechatAutoreplyRule 字段常量表
     */
    public class FIELDS {
        public static final String ID = "id";
        public static final String ACCOUNT_ID = "account_id";
        public static final String RULE_NAME = "rule_name";
        public static final String REPLY_MODE = "reply_mode";
        public static final String KEYWORD_INFO = "keyword_info";
        public static final String REPLY_INFO = "reply_info";
        public static final String SITE_ID = "site_id";
        public static final String LAST_MODIFY_TIME = "last_modify_time";
    }

    public static final String TABLE_NAME = "wechat_autoreply_rule";

}
