package net.ymate.module.wechat.model;

import net.ymate.platform.core.beans.annotation.PropertyState;
import net.ymate.platform.persistence.annotation.Entity;
import net.ymate.platform.persistence.annotation.Id;
import net.ymate.platform.persistence.annotation.Property;
import net.ymate.platform.persistence.jdbc.support.BaseEntity;

/**
 * WechatLocation generated By EntityGenerator on 2016/07/05 上午 02:06:09
 *
 * @author YMP
 * @version 1.0
 */
@Entity("wechat_location")
public class WechatLocation extends BaseEntity<WechatLocation, String> {

    private static final long serialVersionUID = 1L;

    @Id
    @Property(name = "id", nullable = false, length = 32)
    @PropertyState(propertyName = "id")
    private String id;

    @Property(name = "wx_uid", nullable = false, length = 32)
    @PropertyState(propertyName = "wx_uid")
    private String wxUid;

    @Property(name = "location_lon", nullable = false, length = 20)
    @PropertyState(propertyName = "location_lon")
    private Long locationLon;

    @Property(name = "location_lat", nullable = false, length = 20)
    @PropertyState(propertyName = "location_lat")
    private Long locationLat;

    @Property(name = "precision", nullable = false, length = 20)
    @PropertyState(propertyName = "precision")
    private Long precision;

    @Property(name = "label", length = 100)
    @PropertyState(propertyName = "label")
    private String label;

    @Property(name = "create_time", nullable = false, length = 13)
    @PropertyState(propertyName = "create_time")
    private Long createTime;

    @Property(name = "account_id", nullable = false, length = 32)
    @PropertyState(propertyName = "account_id")
    private String accountId;

    @Property(name = "site_id", nullable = false, length = 32)
    @PropertyState(propertyName = "site_id")
    private String siteId;

    @Property(name = "remark", length = 200)
    @PropertyState(propertyName = "remark")
    private String remark;

    /**
     * 构造器
     */
    public WechatLocation() {
    }

    /**
     * 构造器
     *
     * @param id
     * @param wxUid
     * @param locationLon
     * @param locationLat
     * @param precision
     * @param createTime
     * @param accountId
     * @param siteId
     */
    public WechatLocation(String id, String wxUid, Long locationLon, Long locationLat, Long precision, Long createTime, String accountId, String siteId) {
        this.id = id;
        this.wxUid = wxUid;
        this.locationLon = locationLon;
        this.locationLat = locationLat;
        this.precision = precision;
        this.createTime = createTime;
        this.accountId = accountId;
        this.siteId = siteId;
    }

    /**
     * 构造器
     *
     * @param id
     * @param wxUid
     * @param locationLon
     * @param locationLat
     * @param precision
     * @param label
     * @param createTime
     * @param accountId
     * @param siteId
     * @param remark
     */
    public WechatLocation(String id, String wxUid, Long locationLon, Long locationLat, Long precision, String label, Long createTime, String accountId, String siteId, String remark) {
        this.id = id;
        this.wxUid = wxUid;
        this.locationLon = locationLon;
        this.locationLat = locationLat;
        this.precision = precision;
        this.label = label;
        this.createTime = createTime;
        this.accountId = accountId;
        this.siteId = siteId;
        this.remark = remark;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }


    /**
     * @return the wxUid
     */
    public String getWxUid() {
        return wxUid;
    }

    /**
     * @param wxUid the wxUid to set
     */
    public void setWxUid(String wxUid) {
        this.wxUid = wxUid;
    }

    /**
     * @return the locationLon
     */
    public Long getLocationLon() {
        return locationLon;
    }

    /**
     * @param locationLon the locationLon to set
     */
    public void setLocationLon(Long locationLon) {
        this.locationLon = locationLon;
    }

    /**
     * @return the locationLat
     */
    public Long getLocationLat() {
        return locationLat;
    }

    /**
     * @param locationLat the locationLat to set
     */
    public void setLocationLat(Long locationLat) {
        this.locationLat = locationLat;
    }

    /**
     * @return the precision
     */
    public Long getPrecision() {
        return precision;
    }

    /**
     * @param precision the precision to set
     */
    public void setPrecision(Long precision) {
        this.precision = precision;
    }

    /**
     * @return the label
     */
    public String getLabel() {
        return label;
    }

    /**
     * @param label the label to set
     */
    public void setLabel(String label) {
        this.label = label;
    }

    /**
     * @return the createTime
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * @param createTime the createTime to set
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * @return the accountId
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * @param accountId the accountId to set
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    /**
     * @return the siteId
     */
    public String getSiteId() {
        return siteId;
    }

    /**
     * @param siteId the siteId to set
     */
    public void setSiteId(String siteId) {
        this.siteId = siteId;
    }

    /**
     * @return the remark
     */
    public String getRemark() {
        return remark;
    }

    /**
     * @param remark the remark to set
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }


    //
    // Chain
    //

    public static WechatLocationBuilder builder() {
        return new WechatLocationBuilder();
    }

    public WechatLocationBuilder bind() {
        return new WechatLocationBuilder(this);
    }

    public static class WechatLocationBuilder {

        private WechatLocation _model;

        public WechatLocationBuilder() {
            _model = new WechatLocation();
        }

        public WechatLocationBuilder(WechatLocation model) {
            _model = model;
        }

        public WechatLocation build() {
            return _model;
        }

        public String id() {
            return _model.getId();
        }

        public WechatLocationBuilder id(String id) {
            _model.setId(id);
            return this;
        }

        public String wxUid() {
            return _model.getWxUid();
        }

        public WechatLocationBuilder wxUid(String wxUid) {
            _model.setWxUid(wxUid);
            return this;
        }

        public Long locationLon() {
            return _model.getLocationLon();
        }

        public WechatLocationBuilder locationLon(Long locationLon) {
            _model.setLocationLon(locationLon);
            return this;
        }

        public Long locationLat() {
            return _model.getLocationLat();
        }

        public WechatLocationBuilder locationLat(Long locationLat) {
            _model.setLocationLat(locationLat);
            return this;
        }

        public Long precision() {
            return _model.getPrecision();
        }

        public WechatLocationBuilder precision(Long precision) {
            _model.setPrecision(precision);
            return this;
        }

        public String label() {
            return _model.getLabel();
        }

        public WechatLocationBuilder label(String label) {
            _model.setLabel(label);
            return this;
        }

        public Long createTime() {
            return _model.getCreateTime();
        }

        public WechatLocationBuilder createTime(Long createTime) {
            _model.setCreateTime(createTime);
            return this;
        }

        public String accountId() {
            return _model.getAccountId();
        }

        public WechatLocationBuilder accountId(String accountId) {
            _model.setAccountId(accountId);
            return this;
        }

        public String siteId() {
            return _model.getSiteId();
        }

        public WechatLocationBuilder siteId(String siteId) {
            _model.setSiteId(siteId);
            return this;
        }

        public String remark() {
            return _model.getRemark();
        }

        public WechatLocationBuilder remark(String remark) {
            _model.setRemark(remark);
            return this;
        }

    }

    /**
     * WechatLocation 字段常量表
     */
    public class FIELDS {
        public static final String ID = "id";
        public static final String WX_UID = "wx_uid";
        public static final String LOCATION_LON = "location_lon";
        public static final String LOCATION_LAT = "location_lat";
        public static final String PRECISION = "precision";
        public static final String LABEL = "label";
        public static final String CREATE_TIME = "create_time";
        public static final String ACCOUNT_ID = "account_id";
        public static final String SITE_ID = "site_id";
        public static final String REMARK = "remark";
    }

    public static final String TABLE_NAME = "wechat_location";

}
