package net.ymate.module.wechat.model;

import net.ymate.platform.core.beans.annotation.PropertyState;
import net.ymate.platform.persistence.annotation.Default;
import net.ymate.platform.persistence.annotation.Entity;
import net.ymate.platform.persistence.annotation.Id;
import net.ymate.platform.persistence.annotation.Property;
import net.ymate.platform.persistence.jdbc.support.BaseEntity;

/**
 * WechatToken generated By EntityGenerator on 2016/07/09 上午 02:22:54
 *
 * @author YMP
 * @version 1.0
 */
@Entity("wechat_token")
public class WechatToken extends BaseEntity<WechatToken, java.lang.String> {

    private static final long serialVersionUID = 1L;

    @Id
    @Property(name = "id", nullable = false, length = 32)
    @PropertyState(propertyName = "id")
    private java.lang.String id;

    @Property(name = "account_id", nullable = false, length = 32)
    @PropertyState(propertyName = "account_id")
    private java.lang.String accountId;

    @Property(name = "site_id", nullable = false, length = 32)
    @PropertyState(propertyName = "site_id")
    private java.lang.String siteId;

    @Property(name = "access_token", length = 512)
    @PropertyState(propertyName = "access_token")
    private java.lang.String accessToken;

    @Property(name = "access_token_expired_time", length = 13)
    @Default("0")
    @PropertyState(propertyName = "access_token_expired_time")
    private java.lang.Long accessTokenExpiredTime;

    @Property(name = "js_ticket", length = 512)
    @PropertyState(propertyName = "js_ticket")
    private java.lang.String jsTicket;

    @Property(name = "js_ticket_expired_time", length = 13)
    @Default("0")
    @PropertyState(propertyName = "js_ticket_expired_time")
    private java.lang.Long jsTicketExpiredTime;

    @Property(name = "last_modify_time", nullable = false, length = 13)
    @PropertyState(propertyName = "last_modify_time")
    private java.lang.Long lastModifyTime;

    /**
     * 构造器
     */
    public WechatToken() {
    }

    /**
     * 构造器
     *
     * @param id
     * @param accountId
     * @param siteId
     * @param lastModifyTime
     */
    public WechatToken(java.lang.String id, java.lang.String accountId, java.lang.String siteId, java.lang.Long lastModifyTime) {
        this.id = id;
        this.accountId = accountId;
        this.siteId = siteId;
        this.lastModifyTime = lastModifyTime;
    }

    /**
     * 构造器
     *
     * @param id
     * @param accountId
     * @param siteId
     * @param accessToken
     * @param accessTokenExpiredTime
     * @param jsTicket
     * @param jsTicketExpiredTime
     * @param lastModifyTime
     */
    public WechatToken(java.lang.String id, java.lang.String accountId, java.lang.String siteId, java.lang.String accessToken, java.lang.Long accessTokenExpiredTime, java.lang.String jsTicket, java.lang.Long jsTicketExpiredTime, java.lang.Long lastModifyTime) {
        this.id = id;
        this.accountId = accountId;
        this.siteId = siteId;
        this.accessToken = accessToken;
        this.accessTokenExpiredTime = accessTokenExpiredTime;
        this.jsTicket = jsTicket;
        this.jsTicketExpiredTime = jsTicketExpiredTime;
        this.lastModifyTime = lastModifyTime;
    }

    public java.lang.String getId() {
        return id;
    }

    public void setId(java.lang.String id) {
        this.id = id;
    }


    /**
     * @return the accountId
     */
    public java.lang.String getAccountId() {
        return accountId;
    }

    /**
     * @param accountId the accountId to set
     */
    public void setAccountId(java.lang.String accountId) {
        this.accountId = accountId;
    }

    /**
     * @return the siteId
     */
    public java.lang.String getSiteId() {
        return siteId;
    }

    /**
     * @param siteId the siteId to set
     */
    public void setSiteId(java.lang.String siteId) {
        this.siteId = siteId;
    }

    /**
     * @return the accessToken
     */
    public java.lang.String getAccessToken() {
        return accessToken;
    }

    /**
     * @param accessToken the accessToken to set
     */
    public void setAccessToken(java.lang.String accessToken) {
        this.accessToken = accessToken;
    }

    /**
     * @return the accessTokenExpiredTime
     */
    public java.lang.Long getAccessTokenExpiredTime() {
        return accessTokenExpiredTime;
    }

    /**
     * @param accessTokenExpiredTime the accessTokenExpiredTime to set
     */
    public void setAccessTokenExpiredTime(java.lang.Long accessTokenExpiredTime) {
        this.accessTokenExpiredTime = accessTokenExpiredTime;
    }

    /**
     * @return the jsTicket
     */
    public java.lang.String getJsTicket() {
        return jsTicket;
    }

    /**
     * @param jsTicket the jsTicket to set
     */
    public void setJsTicket(java.lang.String jsTicket) {
        this.jsTicket = jsTicket;
    }

    /**
     * @return the jsTicketExpiredTime
     */
    public java.lang.Long getJsTicketExpiredTime() {
        return jsTicketExpiredTime;
    }

    /**
     * @param jsTicketExpiredTime the jsTicketExpiredTime to set
     */
    public void setJsTicketExpiredTime(java.lang.Long jsTicketExpiredTime) {
        this.jsTicketExpiredTime = jsTicketExpiredTime;
    }

    /**
     * @return the lastModifyTime
     */
    public java.lang.Long getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * @param lastModifyTime the lastModifyTime to set
     */
    public void setLastModifyTime(java.lang.Long lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }


    //
    // Chain
    //

    public static WechatTokenBuilder builder() {
        return new WechatTokenBuilder();
    }

    public WechatTokenBuilder bind() {
        return new WechatTokenBuilder(this);
    }

    public static class WechatTokenBuilder {

        private WechatToken _model;

        public WechatTokenBuilder() {
            _model = new WechatToken();
        }

        public WechatTokenBuilder(WechatToken model) {
            _model = model;
        }

        public WechatToken build() {
            return _model;
        }

        public java.lang.String id() {
            return _model.getId();
        }

        public WechatTokenBuilder id(java.lang.String id) {
            _model.setId(id);
            return this;
        }

        public java.lang.String accountId() {
            return _model.getAccountId();
        }

        public WechatTokenBuilder accountId(java.lang.String accountId) {
            _model.setAccountId(accountId);
            return this;
        }

        public java.lang.String siteId() {
            return _model.getSiteId();
        }

        public WechatTokenBuilder siteId(java.lang.String siteId) {
            _model.setSiteId(siteId);
            return this;
        }

        public java.lang.String accessToken() {
            return _model.getAccessToken();
        }

        public WechatTokenBuilder accessToken(java.lang.String accessToken) {
            _model.setAccessToken(accessToken);
            return this;
        }

        public java.lang.Long accessTokenExpiredTime() {
            return _model.getAccessTokenExpiredTime();
        }

        public WechatTokenBuilder accessTokenExpiredTime(java.lang.Long accessTokenExpiredTime) {
            _model.setAccessTokenExpiredTime(accessTokenExpiredTime);
            return this;
        }

        public java.lang.String jsTicket() {
            return _model.getJsTicket();
        }

        public WechatTokenBuilder jsTicket(java.lang.String jsTicket) {
            _model.setJsTicket(jsTicket);
            return this;
        }

        public java.lang.Long jsTicketExpiredTime() {
            return _model.getJsTicketExpiredTime();
        }

        public WechatTokenBuilder jsTicketExpiredTime(java.lang.Long jsTicketExpiredTime) {
            _model.setJsTicketExpiredTime(jsTicketExpiredTime);
            return this;
        }

        public java.lang.Long lastModifyTime() {
            return _model.getLastModifyTime();
        }

        public WechatTokenBuilder lastModifyTime(java.lang.Long lastModifyTime) {
            _model.setLastModifyTime(lastModifyTime);
            return this;
        }

    }

    /**
     * WechatToken 字段常量表
     */
    public class FIELDS {
        public static final String ID = "id";
        public static final String ACCOUNT_ID = "account_id";
        public static final String SITE_ID = "site_id";
        public static final String ACCESS_TOKEN = "access_token";
        public static final String ACCESS_TOKEN_EXPIRED_TIME = "access_token_expired_time";
        public static final String JS_TICKET = "js_ticket";
        public static final String JS_TICKET_EXPIRED_TIME = "js_ticket_expired_time";
        public static final String LAST_MODIFY_TIME = "last_modify_time";
    }

    public static final String TABLE_NAME = "wechat_token";

}
