package net.ymate.module.wechat.model;

import net.ymate.platform.core.beans.annotation.PropertyState;
import net.ymate.platform.persistence.annotation.Default;
import net.ymate.platform.persistence.annotation.Entity;
import net.ymate.platform.persistence.annotation.Id;
import net.ymate.platform.persistence.annotation.Property;
import net.ymate.platform.persistence.jdbc.support.BaseEntity;

/**
 * WechatAccount generated By EntityGenerator on 2016/07/05 上午 02:06:09
 *
 * @author YMP
 * @version 1.0
 */
@Entity("wechat_account")
public class WechatAccount extends BaseEntity<WechatAccount, java.lang.String> {

    private static final long serialVersionUID = 1L;

    @Id
    @Property(name = "id", nullable = false, length = 32)
    @PropertyState(propertyName = "id")
    private java.lang.String id;

    @Property(name = "name", nullable = false, length = 50)
    @PropertyState(propertyName = "name")
    private java.lang.String name;

    @Property(name = "wechat", nullable = false, length = 50)
    @PropertyState(propertyName = "wechat")
    private java.lang.String wechat;

    @Property(name = "account_id", nullable = false, length = 32)
    @PropertyState(propertyName = "account_id")
    private java.lang.String accountId;

    @Property(name = "app_id", nullable = false, length = 50)
    @PropertyState(propertyName = "app_id")
    private java.lang.String appId;

    @Property(name = "app_secret", nullable = false, length = 100)
    @PropertyState(propertyName = "app_secret")
    private java.lang.String appSecret;

    @Property(name = "app_aes_key", length = 50)
    @PropertyState(propertyName = "app_aes_key")
    private java.lang.String appAesKey;

    @Property(name = "last_app_aes_key", length = 50)
    @PropertyState(propertyName = "last_app_aes_key")
    private java.lang.String lastAppAesKey;

    @Property(name = "host", length = 255)
    @PropertyState(propertyName = "host")
    private java.lang.String host;

    @Property(name = "redirect_uri", length = 255)
    @PropertyState(propertyName = "redirect_uri")
    private java.lang.String redirectUri;

    @Property(name = "icon_url", length = 255)
    @PropertyState(propertyName = "icon_url")
    private java.lang.String iconUrl;

    @Property(name = "qr_code", length = 255)
    @PropertyState(propertyName = "qr_code")
    private java.lang.String qrCode;

    @Property(name = "token", nullable = false, length = 32)
    @PropertyState(propertyName = "token")
    private java.lang.String token;

    @Property(name = "type", unsigned = true, length = 2)
    @Default("0")
    @PropertyState(propertyName = "type")
    private java.lang.Integer type;

    @Property(name = "country", length = 32)
    @Default("")
    @PropertyState(propertyName = "country")
    private java.lang.String country;

    @Property(name = "province", length = 32)
    @PropertyState(propertyName = "province")
    private java.lang.String province;

    @Property(name = "city", length = 32)
    @PropertyState(propertyName = "city")
    private java.lang.String city;

    @Property(name = "location_addr", length = 200)
    @PropertyState(propertyName = "location_addr")
    private java.lang.String locationAddr;

    @Property(name = "location_lon", length = 20)
    @Default("0")
    @PropertyState(propertyName = "location_lon")
    private java.lang.Long locationLon;

    @Property(name = "location_lat", length = 20)
    @Default("0")
    @PropertyState(propertyName = "location_lat")
    private java.lang.Long locationLat;

    @Property(name = "menu", length = 16383)
    @PropertyState(propertyName = "menu")
    private java.lang.String menu;

    @Property(name = "summary", length = 16383)
    @PropertyState(propertyName = "summary")
    private java.lang.String summary;

    @Property(name = "is_verified", unsigned = true, length = 1)
    @Default("0")
    @PropertyState(propertyName = "is_verified")
    private java.lang.Integer isVerified;

    @Property(name = "is_deleted", unsigned = true, length = 1)
    @Default("0")
    @PropertyState(propertyName = "is_deleted")
    private java.lang.Integer isDeleted;

    @Property(name = "is_msg_encrypted", unsigned = true, length = 1)
    @Default("0")
    @PropertyState(propertyName = "is_msg_encrypted")
    private java.lang.Integer isMsgEncrypted;

    @Property(name = "mch_id", length = 32)
    @PropertyState(propertyName = "mch_id")
    private java.lang.String mchId;

    @Property(name = "mch_key", length = 32)
    @PropertyState(propertyName = "mch_key")
    private java.lang.String mchKey;

    @Property(name = "notify_url", length = 255)
    @PropertyState(propertyName = "notify_url")
    private java.lang.String notifyUrl;

    @Property(name = "cert_file_path", length = 255)
    @PropertyState(propertyName = "cert_file_path")
    private java.lang.String certFilePath;

    @Property(name = "status", unsigned = true, length = 2)
    @Default("0")
    @PropertyState(propertyName = "status")
    private java.lang.Integer status;

    @Property(name = "site_id", nullable = false, length = 32)
    @PropertyState(propertyName = "site_id")
    private java.lang.String siteId;

    @Property(name = "remark", length = 200)
    @PropertyState(propertyName = "remark")
    private java.lang.String remark;

    @Property(name = "create_time", nullable = false, length = 13)
    @PropertyState(propertyName = "create_time")
    private java.lang.Long createTime;

    @Property(name = "last_modify_time", length = 13)
    @Default("0")
    @PropertyState(propertyName = "last_modify_time")
    private java.lang.Long lastModifyTime;

    /**
     * 构造器
     */
    public WechatAccount() {
    }

    /**
     * 构造器
     *
     * @param id
     * @param name
     * @param wechat
     * @param accountId
     * @param appId
     * @param appSecret
     * @param token
     * @param siteId
     * @param createTime
     */
    public WechatAccount(java.lang.String id, java.lang.String name, java.lang.String wechat, java.lang.String accountId, java.lang.String appId, java.lang.String appSecret, java.lang.String token, java.lang.String siteId, java.lang.Long createTime) {
        this.id = id;
        this.name = name;
        this.wechat = wechat;
        this.accountId = accountId;
        this.appId = appId;
        this.appSecret = appSecret;
        this.token = token;
        this.siteId = siteId;
        this.createTime = createTime;
    }

    /**
     * 构造器
     *
     * @param id
     * @param name
     * @param wechat
     * @param accountId
     * @param appId
     * @param appSecret
     * @param appAesKey
     * @param lastAppAesKey
     * @param host
     * @param redirectUri
     * @param iconUrl
     * @param qrCode
     * @param token
     * @param type
     * @param country
     * @param province
     * @param city
     * @param locationAddr
     * @param locationLon
     * @param locationLat
     * @param menu
     * @param summary
     * @param isVerified
     * @param isDeleted
     * @param isMsgEncrypted
     * @param mchId
     * @param mchKey
     * @param notifyUrl
     * @param certFilePath
     * @param status
     * @param siteId
     * @param remark
     * @param createTime
     * @param lastModifyTime
     */
    public WechatAccount(java.lang.String id, java.lang.String name, java.lang.String wechat, java.lang.String accountId, java.lang.String appId, java.lang.String appSecret, java.lang.String appAesKey, java.lang.String lastAppAesKey, java.lang.String host, java.lang.String redirectUri, java.lang.String iconUrl, java.lang.String qrCode, java.lang.String token, java.lang.Integer type, java.lang.String country, java.lang.String province, java.lang.String city, java.lang.String locationAddr, java.lang.Long locationLon, java.lang.Long locationLat, java.lang.String menu, java.lang.String summary, java.lang.Integer isVerified, java.lang.Integer isDeleted, java.lang.Integer isMsgEncrypted, java.lang.String mchId, java.lang.String mchKey, java.lang.String notifyUrl, java.lang.String certFilePath, java.lang.Integer status, java.lang.String siteId, java.lang.String remark, java.lang.Long createTime, java.lang.Long lastModifyTime) {
        this.id = id;
        this.name = name;
        this.wechat = wechat;
        this.accountId = accountId;
        this.appId = appId;
        this.appSecret = appSecret;
        this.appAesKey = appAesKey;
        this.lastAppAesKey = lastAppAesKey;
        this.host = host;
        this.redirectUri = redirectUri;
        this.iconUrl = iconUrl;
        this.qrCode = qrCode;
        this.token = token;
        this.type = type;
        this.country = country;
        this.province = province;
        this.city = city;
        this.locationAddr = locationAddr;
        this.locationLon = locationLon;
        this.locationLat = locationLat;
        this.menu = menu;
        this.summary = summary;
        this.isVerified = isVerified;
        this.isDeleted = isDeleted;
        this.isMsgEncrypted = isMsgEncrypted;
        this.mchId = mchId;
        this.mchKey = mchKey;
        this.notifyUrl = notifyUrl;
        this.certFilePath = certFilePath;
        this.status = status;
        this.siteId = siteId;
        this.remark = remark;
        this.createTime = createTime;
        this.lastModifyTime = lastModifyTime;
    }

    public java.lang.String getId() {
        return id;
    }

    public void setId(java.lang.String id) {
        this.id = id;
    }


    /**
     * @return the name
     */
    public java.lang.String getName() {
        return name;
    }

    /**
     * @param name the name to set
     */
    public void setName(java.lang.String name) {
        this.name = name;
    }

    /**
     * @return the wechat
     */
    public java.lang.String getWechat() {
        return wechat;
    }

    /**
     * @param wechat the wechat to set
     */
    public void setWechat(java.lang.String wechat) {
        this.wechat = wechat;
    }

    /**
     * @return the accountId
     */
    public java.lang.String getAccountId() {
        return accountId;
    }

    /**
     * @param accountId the accountId to set
     */
    public void setAccountId(java.lang.String accountId) {
        this.accountId = accountId;
    }

    /**
     * @return the appId
     */
    public java.lang.String getAppId() {
        return appId;
    }

    /**
     * @param appId the appId to set
     */
    public void setAppId(java.lang.String appId) {
        this.appId = appId;
    }

    /**
     * @return the appSecret
     */
    public java.lang.String getAppSecret() {
        return appSecret;
    }

    /**
     * @param appSecret the appSecret to set
     */
    public void setAppSecret(java.lang.String appSecret) {
        this.appSecret = appSecret;
    }

    /**
     * @return the appAesKey
     */
    public java.lang.String getAppAesKey() {
        return appAesKey;
    }

    /**
     * @param appAesKey the appAesKey to set
     */
    public void setAppAesKey(java.lang.String appAesKey) {
        this.appAesKey = appAesKey;
    }

    /**
     * @return the lastAppAesKey
     */
    public java.lang.String getLastAppAesKey() {
        return lastAppAesKey;
    }

    /**
     * @param lastAppAesKey the lastAppAesKey to set
     */
    public void setLastAppAesKey(java.lang.String lastAppAesKey) {
        this.lastAppAesKey = lastAppAesKey;
    }

    /**
     * @return the host
     */
    public java.lang.String getHost() {
        return host;
    }

    /**
     * @param host the host to set
     */
    public void setHost(java.lang.String host) {
        this.host = host;
    }

    /**
     * @return the redirectUri
     */
    public java.lang.String getRedirectUri() {
        return redirectUri;
    }

    /**
     * @param redirectUri the redirectUri to set
     */
    public void setRedirectUri(java.lang.String redirectUri) {
        this.redirectUri = redirectUri;
    }

    /**
     * @return the iconUrl
     */
    public java.lang.String getIconUrl() {
        return iconUrl;
    }

    /**
     * @param iconUrl the iconUrl to set
     */
    public void setIconUrl(java.lang.String iconUrl) {
        this.iconUrl = iconUrl;
    }

    /**
     * @return the qrCode
     */
    public java.lang.String getQrCode() {
        return qrCode;
    }

    /**
     * @param qrCode the qrCode to set
     */
    public void setQrCode(java.lang.String qrCode) {
        this.qrCode = qrCode;
    }

    /**
     * @return the token
     */
    public java.lang.String getToken() {
        return token;
    }

    /**
     * @param token the token to set
     */
    public void setToken(java.lang.String token) {
        this.token = token;
    }

    /**
     * @return the type
     */
    public java.lang.Integer getType() {
        return type;
    }

    /**
     * @param type the type to set
     */
    public void setType(java.lang.Integer type) {
        this.type = type;
    }

    /**
     * @return the country
     */
    public java.lang.String getCountry() {
        return country;
    }

    /**
     * @param country the country to set
     */
    public void setCountry(java.lang.String country) {
        this.country = country;
    }

    /**
     * @return the province
     */
    public java.lang.String getProvince() {
        return province;
    }

    /**
     * @param province the province to set
     */
    public void setProvince(java.lang.String province) {
        this.province = province;
    }

    /**
     * @return the city
     */
    public java.lang.String getCity() {
        return city;
    }

    /**
     * @param city the city to set
     */
    public void setCity(java.lang.String city) {
        this.city = city;
    }

    /**
     * @return the locationAddr
     */
    public java.lang.String getLocationAddr() {
        return locationAddr;
    }

    /**
     * @param locationAddr the locationAddr to set
     */
    public void setLocationAddr(java.lang.String locationAddr) {
        this.locationAddr = locationAddr;
    }

    /**
     * @return the locationLon
     */
    public java.lang.Long getLocationLon() {
        return locationLon;
    }

    /**
     * @param locationLon the locationLon to set
     */
    public void setLocationLon(java.lang.Long locationLon) {
        this.locationLon = locationLon;
    }

    /**
     * @return the locationLat
     */
    public java.lang.Long getLocationLat() {
        return locationLat;
    }

    /**
     * @param locationLat the locationLat to set
     */
    public void setLocationLat(java.lang.Long locationLat) {
        this.locationLat = locationLat;
    }

    /**
     * @return the menu
     */
    public java.lang.String getMenu() {
        return menu;
    }

    /**
     * @param menu the menu to set
     */
    public void setMenu(java.lang.String menu) {
        this.menu = menu;
    }

    /**
     * @return the summary
     */
    public java.lang.String getSummary() {
        return summary;
    }

    /**
     * @param summary the summary to set
     */
    public void setSummary(java.lang.String summary) {
        this.summary = summary;
    }

    /**
     * @return the isVerified
     */
    public java.lang.Integer getIsVerified() {
        return isVerified;
    }

    /**
     * @param isVerified the isVerified to set
     */
    public void setIsVerified(java.lang.Integer isVerified) {
        this.isVerified = isVerified;
    }

    /**
     * @return the isDeleted
     */
    public java.lang.Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * @param isDeleted the isDeleted to set
     */
    public void setIsDeleted(java.lang.Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * @return the isMsgEncrypted
     */
    public java.lang.Integer getIsMsgEncrypted() {
        return isMsgEncrypted;
    }

    /**
     * @param isMsgEncrypted the isMsgEncrypted to set
     */
    public void setIsMsgEncrypted(java.lang.Integer isMsgEncrypted) {
        this.isMsgEncrypted = isMsgEncrypted;
    }

    /**
     * @return the mchId
     */
    public java.lang.String getMchId() {
        return mchId;
    }

    /**
     * @param mchId the mchId to set
     */
    public void setMchId(java.lang.String mchId) {
        this.mchId = mchId;
    }

    /**
     * @return the mchKey
     */
    public java.lang.String getMchKey() {
        return mchKey;
    }

    /**
     * @param mchKey the mchKey to set
     */
    public void setMchKey(java.lang.String mchKey) {
        this.mchKey = mchKey;
    }

    /**
     * @return the notifyUrl
     */
    public java.lang.String getNotifyUrl() {
        return notifyUrl;
    }

    /**
     * @param notifyUrl the notifyUrl to set
     */
    public void setNotifyUrl(java.lang.String notifyUrl) {
        this.notifyUrl = notifyUrl;
    }

    /**
     * @return the certFilePath
     */
    public java.lang.String getCertFilePath() {
        return certFilePath;
    }

    /**
     * @param certFilePath the certFilePath to set
     */
    public void setCertFilePath(java.lang.String certFilePath) {
        this.certFilePath = certFilePath;
    }

    /**
     * @return the status
     */
    public java.lang.Integer getStatus() {
        return status;
    }

    /**
     * @param status the status to set
     */
    public void setStatus(java.lang.Integer status) {
        this.status = status;
    }

    /**
     * @return the siteId
     */
    public java.lang.String getSiteId() {
        return siteId;
    }

    /**
     * @param siteId the siteId to set
     */
    public void setSiteId(java.lang.String siteId) {
        this.siteId = siteId;
    }

    /**
     * @return the remark
     */
    public java.lang.String getRemark() {
        return remark;
    }

    /**
     * @param remark the remark to set
     */
    public void setRemark(java.lang.String remark) {
        this.remark = remark;
    }

    /**
     * @return the createTime
     */
    public java.lang.Long getCreateTime() {
        return createTime;
    }

    /**
     * @param createTime the createTime to set
     */
    public void setCreateTime(java.lang.Long createTime) {
        this.createTime = createTime;
    }

    /**
     * @return the lastModifyTime
     */
    public java.lang.Long getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * @param lastModifyTime the lastModifyTime to set
     */
    public void setLastModifyTime(java.lang.Long lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }


    //
    // Chain
    //

    public static WechatAccountBuilder builder() {
        return new WechatAccountBuilder();
    }

    public WechatAccountBuilder bind() {
        return new WechatAccountBuilder(this);
    }

    public static class WechatAccountBuilder {

        private WechatAccount _model;

        public WechatAccountBuilder() {
            _model = new WechatAccount();
        }

        public WechatAccountBuilder(WechatAccount model) {
            _model = model;
        }

        public WechatAccount build() {
            return _model;
        }

        public java.lang.String id() {
            return _model.getId();
        }

        public WechatAccountBuilder id(java.lang.String id) {
            _model.setId(id);
            return this;
        }

        public java.lang.String name() {
            return _model.getName();
        }

        public WechatAccountBuilder name(java.lang.String name) {
            _model.setName(name);
            return this;
        }

        public java.lang.String wechat() {
            return _model.getWechat();
        }

        public WechatAccountBuilder wechat(java.lang.String wechat) {
            _model.setWechat(wechat);
            return this;
        }

        public java.lang.String accountId() {
            return _model.getAccountId();
        }

        public WechatAccountBuilder accountId(java.lang.String accountId) {
            _model.setAccountId(accountId);
            return this;
        }

        public java.lang.String appId() {
            return _model.getAppId();
        }

        public WechatAccountBuilder appId(java.lang.String appId) {
            _model.setAppId(appId);
            return this;
        }

        public java.lang.String appSecret() {
            return _model.getAppSecret();
        }

        public WechatAccountBuilder appSecret(java.lang.String appSecret) {
            _model.setAppSecret(appSecret);
            return this;
        }

        public java.lang.String appAesKey() {
            return _model.getAppAesKey();
        }

        public WechatAccountBuilder appAesKey(java.lang.String appAesKey) {
            _model.setAppAesKey(appAesKey);
            return this;
        }

        public java.lang.String lastAppAesKey() {
            return _model.getLastAppAesKey();
        }

        public WechatAccountBuilder lastAppAesKey(java.lang.String lastAppAesKey) {
            _model.setLastAppAesKey(lastAppAesKey);
            return this;
        }

        public java.lang.String host() {
            return _model.getHost();
        }

        public WechatAccountBuilder host(java.lang.String host) {
            _model.setHost(host);
            return this;
        }

        public java.lang.String redirectUri() {
            return _model.getRedirectUri();
        }

        public WechatAccountBuilder redirectUri(java.lang.String redirectUri) {
            _model.setRedirectUri(redirectUri);
            return this;
        }

        public java.lang.String iconUrl() {
            return _model.getIconUrl();
        }

        public WechatAccountBuilder iconUrl(java.lang.String iconUrl) {
            _model.setIconUrl(iconUrl);
            return this;
        }

        public java.lang.String qrCode() {
            return _model.getQrCode();
        }

        public WechatAccountBuilder qrCode(java.lang.String qrCode) {
            _model.setQrCode(qrCode);
            return this;
        }

        public java.lang.String token() {
            return _model.getToken();
        }

        public WechatAccountBuilder token(java.lang.String token) {
            _model.setToken(token);
            return this;
        }

        public java.lang.Integer type() {
            return _model.getType();
        }

        public WechatAccountBuilder type(java.lang.Integer type) {
            _model.setType(type);
            return this;
        }

        public java.lang.String country() {
            return _model.getCountry();
        }

        public WechatAccountBuilder country(java.lang.String country) {
            _model.setCountry(country);
            return this;
        }

        public java.lang.String province() {
            return _model.getProvince();
        }

        public WechatAccountBuilder province(java.lang.String province) {
            _model.setProvince(province);
            return this;
        }

        public java.lang.String city() {
            return _model.getCity();
        }

        public WechatAccountBuilder city(java.lang.String city) {
            _model.setCity(city);
            return this;
        }

        public java.lang.String locationAddr() {
            return _model.getLocationAddr();
        }

        public WechatAccountBuilder locationAddr(java.lang.String locationAddr) {
            _model.setLocationAddr(locationAddr);
            return this;
        }

        public java.lang.Long locationLon() {
            return _model.getLocationLon();
        }

        public WechatAccountBuilder locationLon(java.lang.Long locationLon) {
            _model.setLocationLon(locationLon);
            return this;
        }

        public java.lang.Long locationLat() {
            return _model.getLocationLat();
        }

        public WechatAccountBuilder locationLat(java.lang.Long locationLat) {
            _model.setLocationLat(locationLat);
            return this;
        }

        public java.lang.String menu() {
            return _model.getMenu();
        }

        public WechatAccountBuilder menu(java.lang.String menu) {
            _model.setMenu(menu);
            return this;
        }

        public java.lang.String summary() {
            return _model.getSummary();
        }

        public WechatAccountBuilder summary(java.lang.String summary) {
            _model.setSummary(summary);
            return this;
        }

        public java.lang.Integer isVerified() {
            return _model.getIsVerified();
        }

        public WechatAccountBuilder isVerified(java.lang.Integer isVerified) {
            _model.setIsVerified(isVerified);
            return this;
        }

        public java.lang.Integer isDeleted() {
            return _model.getIsDeleted();
        }

        public WechatAccountBuilder isDeleted(java.lang.Integer isDeleted) {
            _model.setIsDeleted(isDeleted);
            return this;
        }

        public java.lang.Integer isMsgEncrypted() {
            return _model.getIsMsgEncrypted();
        }

        public WechatAccountBuilder isMsgEncrypted(java.lang.Integer isMsgEncrypted) {
            _model.setIsMsgEncrypted(isMsgEncrypted);
            return this;
        }

        public java.lang.String mchId() {
            return _model.getMchId();
        }

        public WechatAccountBuilder mchId(java.lang.String mchId) {
            _model.setMchId(mchId);
            return this;
        }

        public java.lang.String mchKey() {
            return _model.getMchKey();
        }

        public WechatAccountBuilder mchKey(java.lang.String mchKey) {
            _model.setMchKey(mchKey);
            return this;
        }

        public java.lang.String notifyUrl() {
            return _model.getNotifyUrl();
        }

        public WechatAccountBuilder notifyUrl(java.lang.String notifyUrl) {
            _model.setNotifyUrl(notifyUrl);
            return this;
        }

        public java.lang.String certFilePath() {
            return _model.getCertFilePath();
        }

        public WechatAccountBuilder certFilePath(java.lang.String certFilePath) {
            _model.setCertFilePath(certFilePath);
            return this;
        }

        public java.lang.Integer status() {
            return _model.getStatus();
        }

        public WechatAccountBuilder status(java.lang.Integer status) {
            _model.setStatus(status);
            return this;
        }

        public java.lang.String siteId() {
            return _model.getSiteId();
        }

        public WechatAccountBuilder siteId(java.lang.String siteId) {
            _model.setSiteId(siteId);
            return this;
        }

        public java.lang.String remark() {
            return _model.getRemark();
        }

        public WechatAccountBuilder remark(java.lang.String remark) {
            _model.setRemark(remark);
            return this;
        }

        public java.lang.Long createTime() {
            return _model.getCreateTime();
        }

        public WechatAccountBuilder createTime(java.lang.Long createTime) {
            _model.setCreateTime(createTime);
            return this;
        }

        public java.lang.Long lastModifyTime() {
            return _model.getLastModifyTime();
        }

        public WechatAccountBuilder lastModifyTime(java.lang.Long lastModifyTime) {
            _model.setLastModifyTime(lastModifyTime);
            return this;
        }

    }

    /**
     * WechatAccount 字段常量表
     */
    public class FIELDS {
        public static final String ID = "id";
        public static final String NAME = "name";
        public static final String WECHAT = "wechat";
        public static final String ACCOUNT_ID = "account_id";
        public static final String APP_ID = "app_id";
        public static final String APP_SECRET = "app_secret";
        public static final String APP_AES_KEY = "app_aes_key";
        public static final String LAST_APP_AES_KEY = "last_app_aes_key";
        public static final String HOST = "host";
        public static final String REDIRECT_URI = "redirect_uri";
        public static final String ICON_URL = "icon_url";
        public static final String QR_CODE = "qr_code";
        public static final String TOKEN = "token";
        public static final String TYPE = "type";
        public static final String COUNTRY = "country";
        public static final String PROVINCE = "province";
        public static final String CITY = "city";
        public static final String LOCATION_ADDR = "location_addr";
        public static final String LOCATION_LON = "location_lon";
        public static final String LOCATION_LAT = "location_lat";
        public static final String MENU = "menu";
        public static final String SUMMARY = "summary";
        public static final String IS_VERIFIED = "is_verified";
        public static final String IS_DELETED = "is_deleted";
        public static final String IS_MSG_ENCRYPTED = "is_msg_encrypted";
        public static final String MCH_ID = "mch_id";
        public static final String MCH_KEY = "mch_key";
        public static final String NOTIFY_URL = "notify_url";
        public static final String CERT_FILE_PATH = "cert_file_path";
        public static final String STATUS = "status";
        public static final String SITE_ID = "site_id";
        public static final String REMARK = "remark";
        public static final String CREATE_TIME = "create_time";
        public static final String LAST_MODIFY_TIME = "last_modify_time";
    }

    public static final String TABLE_NAME = "wechat_account";

}
