package net.ymate.module.wechat.model;

import net.ymate.platform.core.beans.annotation.PropertyState;
import net.ymate.platform.persistence.annotation.Default;
import net.ymate.platform.persistence.annotation.Entity;
import net.ymate.platform.persistence.annotation.Id;
import net.ymate.platform.persistence.annotation.Property;
import net.ymate.platform.persistence.jdbc.support.BaseEntity;

/**
 * WechatAutoreply generated By EntityGenerator on 2016/07/11 上午 01:08:18
 *
 * @author YMP
 * @version 1.0
 */
@Entity("wechat_autoreply")
public class WechatAutoreply extends BaseEntity<WechatAutoreply, String> {

    private static final long serialVersionUID = 1L;

    @Id
    @Property(name = "id", nullable = false, length = 32)
    @PropertyState(propertyName = "id")
    private String id;

    @Property(name = "account_id", nullable = false, length = 32)
    @PropertyState(propertyName = "account_id")
    private String accountId;

    @Property(name = "is_autoreply_open", unsigned = true, length = 1)
    @Default("1")
    @PropertyState(propertyName = "is_autoreply_open")
    private Integer isAutoreplyOpen;

    @Property(name = "is_subscribe_reply_open", unsigned = true, length = 1)
    @Default("1")
    @PropertyState(propertyName = "is_subscribe_reply_open")
    private Integer isSubscribeReplyOpen;

    @Property(name = "subscribe_autoreply_type", length = 10)
    @PropertyState(propertyName = "subscribe_autoreply_type")
    private String subscribeAutoreplyType;

    @Property(name = "subscribeautoreply_content", length = 32)
    @PropertyState(propertyName = "subscribeautoreply_content")
    private String subscribeautoreplyContent;

    @Property(name = "default_autoreply_type", length = 10)
    @PropertyState(propertyName = "default_autoreply_type")
    private String defaultAutoreplyType;

    @Property(name = "default_autoreply_content", length = 32)
    @PropertyState(propertyName = "default_autoreply_content")
    private String defaultAutoreplyContent;

    @Property(name = "site_id", nullable = false, length = 32)
    @PropertyState(propertyName = "site_id")
    private String siteId;

    @Property(name = "last_modify_time", length = 13)
    @Default("0")
    @PropertyState(propertyName = "last_modify_time")
    private Long lastModifyTime;

    /**
     * 构造器
     */
    public WechatAutoreply() {
    }

    /**
     * 构造器
     *
     * @param id
     * @param accountId
     * @param siteId
     */
    public WechatAutoreply(String id, String accountId, String siteId) {
        this.id = id;
        this.accountId = accountId;
        this.siteId = siteId;
    }

    /**
     * 构造器
     *
     * @param id
     * @param accountId
     * @param isAutoreplyOpen
     * @param isSubscribeReplyOpen
     * @param subscribeAutoreplyType
     * @param subscribeautoreplyContent
     * @param defaultAutoreplyType
     * @param defaultAutoreplyContent
     * @param siteId
     * @param lastModifyTime
     */
    public WechatAutoreply(String id, String accountId, Integer isAutoreplyOpen, Integer isSubscribeReplyOpen, String subscribeAutoreplyType, String subscribeautoreplyContent, String defaultAutoreplyType, String defaultAutoreplyContent, String siteId, Long lastModifyTime) {
        this.id = id;
        this.accountId = accountId;
        this.isAutoreplyOpen = isAutoreplyOpen;
        this.isSubscribeReplyOpen = isSubscribeReplyOpen;
        this.subscribeAutoreplyType = subscribeAutoreplyType;
        this.subscribeautoreplyContent = subscribeautoreplyContent;
        this.defaultAutoreplyType = defaultAutoreplyType;
        this.defaultAutoreplyContent = defaultAutoreplyContent;
        this.siteId = siteId;
        this.lastModifyTime = lastModifyTime;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }


    /**
     * @return the accountId
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * @param accountId the accountId to set
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    /**
     * @return the isAutoreplyOpen
     */
    public Integer getIsAutoreplyOpen() {
        return isAutoreplyOpen;
    }

    /**
     * @param isAutoreplyOpen the isAutoreplyOpen to set
     */
    public void setIsAutoreplyOpen(Integer isAutoreplyOpen) {
        this.isAutoreplyOpen = isAutoreplyOpen;
    }

    /**
     * @return the isSubscribeReplyOpen
     */
    public Integer getIsSubscribeReplyOpen() {
        return isSubscribeReplyOpen;
    }

    /**
     * @param isSubscribeReplyOpen the isSubscribeReplyOpen to set
     */
    public void setIsSubscribeReplyOpen(Integer isSubscribeReplyOpen) {
        this.isSubscribeReplyOpen = isSubscribeReplyOpen;
    }

    /**
     * @return the subscribeAutoreplyType
     */
    public String getSubscribeAutoreplyType() {
        return subscribeAutoreplyType;
    }

    /**
     * @param subscribeAutoreplyType the subscribeAutoreplyType to set
     */
    public void setSubscribeAutoreplyType(String subscribeAutoreplyType) {
        this.subscribeAutoreplyType = subscribeAutoreplyType;
    }

    /**
     * @return the subscribeautoreplyContent
     */
    public String getSubscribeautoreplyContent() {
        return subscribeautoreplyContent;
    }

    /**
     * @param subscribeautoreplyContent the subscribeautoreplyContent to set
     */
    public void setSubscribeautoreplyContent(String subscribeautoreplyContent) {
        this.subscribeautoreplyContent = subscribeautoreplyContent;
    }

    /**
     * @return the defaultAutoreplyType
     */
    public String getDefaultAutoreplyType() {
        return defaultAutoreplyType;
    }

    /**
     * @param defaultAutoreplyType the defaultAutoreplyType to set
     */
    public void setDefaultAutoreplyType(String defaultAutoreplyType) {
        this.defaultAutoreplyType = defaultAutoreplyType;
    }

    /**
     * @return the defaultAutoreplyContent
     */
    public String getDefaultAutoreplyContent() {
        return defaultAutoreplyContent;
    }

    /**
     * @param defaultAutoreplyContent the defaultAutoreplyContent to set
     */
    public void setDefaultAutoreplyContent(String defaultAutoreplyContent) {
        this.defaultAutoreplyContent = defaultAutoreplyContent;
    }

    /**
     * @return the siteId
     */
    public String getSiteId() {
        return siteId;
    }

    /**
     * @param siteId the siteId to set
     */
    public void setSiteId(String siteId) {
        this.siteId = siteId;
    }

    /**
     * @return the lastModifyTime
     */
    public Long getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * @param lastModifyTime the lastModifyTime to set
     */
    public void setLastModifyTime(Long lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }


    //
    // Chain
    //

    public static WechatAutoreplyBuilder builder() {
        return new WechatAutoreplyBuilder();
    }

    public WechatAutoreplyBuilder bind() {
        return new WechatAutoreplyBuilder(this);
    }

    public static class WechatAutoreplyBuilder {

        private WechatAutoreply _model;

        public WechatAutoreplyBuilder() {
            _model = new WechatAutoreply();
        }

        public WechatAutoreplyBuilder(WechatAutoreply model) {
            _model = model;
        }

        public WechatAutoreply build() {
            return _model;
        }

        public String id() {
            return _model.getId();
        }

        public WechatAutoreplyBuilder id(String id) {
            _model.setId(id);
            return this;
        }

        public String accountId() {
            return _model.getAccountId();
        }

        public WechatAutoreplyBuilder accountId(String accountId) {
            _model.setAccountId(accountId);
            return this;
        }

        public Integer isAutoreplyOpen() {
            return _model.getIsAutoreplyOpen();
        }

        public WechatAutoreplyBuilder isAutoreplyOpen(Integer isAutoreplyOpen) {
            _model.setIsAutoreplyOpen(isAutoreplyOpen);
            return this;
        }

        public Integer isSubscribeReplyOpen() {
            return _model.getIsSubscribeReplyOpen();
        }

        public WechatAutoreplyBuilder isSubscribeReplyOpen(Integer isSubscribeReplyOpen) {
            _model.setIsSubscribeReplyOpen(isSubscribeReplyOpen);
            return this;
        }

        public String subscribeAutoreplyType() {
            return _model.getSubscribeAutoreplyType();
        }

        public WechatAutoreplyBuilder subscribeAutoreplyType(String subscribeAutoreplyType) {
            _model.setSubscribeAutoreplyType(subscribeAutoreplyType);
            return this;
        }

        public String subscribeautoreplyContent() {
            return _model.getSubscribeautoreplyContent();
        }

        public WechatAutoreplyBuilder subscribeautoreplyContent(String subscribeautoreplyContent) {
            _model.setSubscribeautoreplyContent(subscribeautoreplyContent);
            return this;
        }

        public String defaultAutoreplyType() {
            return _model.getDefaultAutoreplyType();
        }

        public WechatAutoreplyBuilder defaultAutoreplyType(String defaultAutoreplyType) {
            _model.setDefaultAutoreplyType(defaultAutoreplyType);
            return this;
        }

        public String defaultAutoreplyContent() {
            return _model.getDefaultAutoreplyContent();
        }

        public WechatAutoreplyBuilder defaultAutoreplyContent(String defaultAutoreplyContent) {
            _model.setDefaultAutoreplyContent(defaultAutoreplyContent);
            return this;
        }

        public String siteId() {
            return _model.getSiteId();
        }

        public WechatAutoreplyBuilder siteId(String siteId) {
            _model.setSiteId(siteId);
            return this;
        }

        public Long lastModifyTime() {
            return _model.getLastModifyTime();
        }

        public WechatAutoreplyBuilder lastModifyTime(Long lastModifyTime) {
            _model.setLastModifyTime(lastModifyTime);
            return this;
        }

    }

    /**
     * WechatAutoreply 字段常量表
     */
    public class FIELDS {
        public static final String ID = "id";
        public static final String ACCOUNT_ID = "account_id";
        public static final String IS_AUTOREPLY_OPEN = "is_autoreply_open";
        public static final String IS_SUBSCRIBE_REPLY_OPEN = "is_subscribe_reply_open";
        public static final String SUBSCRIBE_AUTOREPLY_TYPE = "subscribe_autoreply_type";
        public static final String SUBSCRIBEAUTOREPLY_CONTENT = "subscribeautoreply_content";
        public static final String DEFAULT_AUTOREPLY_TYPE = "default_autoreply_type";
        public static final String DEFAULT_AUTOREPLY_CONTENT = "default_autoreply_content";
        public static final String SITE_ID = "site_id";
        public static final String LAST_MODIFY_TIME = "last_modify_time";
    }

    public static final String TABLE_NAME = "wechat_autoreply";

}
