package net.ymate.module.wechat.model;

import net.ymate.platform.core.beans.annotation.PropertyState;
import net.ymate.platform.persistence.annotation.Default;
import net.ymate.platform.persistence.annotation.Entity;
import net.ymate.platform.persistence.annotation.Id;
import net.ymate.platform.persistence.annotation.Property;
import net.ymate.platform.persistence.jdbc.support.BaseEntity;

/**
 * WechatAccount generated By EntityGenerator on 2016/07/05 上午 02:06:09
 *
 * @author YMP
 * @version 1.0
 */
@Entity("wechat_account")
public class WechatAccount extends BaseEntity<WechatAccount, String> {

    private static final long serialVersionUID = 1L;

    @Id
    @Property(name = "id", nullable = false, length = 32)
    @PropertyState(propertyName = "id")
    private String id;

    @Property(name = "name", nullable = false, length = 50)
    @PropertyState(propertyName = "name")
    private String name;

    @Property(name = "wechat", nullable = false, length = 50)
    @PropertyState(propertyName = "wechat")
    private String wechat;

    @Property(name = "account_id", nullable = false, length = 32)
    @PropertyState(propertyName = "account_id")
    private String accountId;

    @Property(name = "app_id", nullable = false, length = 50)
    @PropertyState(propertyName = "app_id")
    private String appId;

    @Property(name = "app_secret", nullable = false, length = 100)
    @PropertyState(propertyName = "app_secret")
    private String appSecret;

    @Property(name = "app_aes_key", length = 50)
    @PropertyState(propertyName = "app_aes_key")
    private String appAesKey;

    @Property(name = "last_app_aes_key", length = 50)
    @PropertyState(propertyName = "last_app_aes_key")
    private String lastAppAesKey;

    @Property(name = "host", length = 255)
    @PropertyState(propertyName = "host")
    private String host;

    @Property(name = "redirect_uri", length = 255)
    @PropertyState(propertyName = "redirect_uri")
    private String redirectUri;

    @Property(name = "icon_url", length = 255)
    @PropertyState(propertyName = "icon_url")
    private String iconUrl;

    @Property(name = "qr_code", length = 255)
    @PropertyState(propertyName = "qr_code")
    private String qrCode;

    @Property(name = "token", nullable = false, length = 32)
    @PropertyState(propertyName = "token")
    private String token;

    @Property(name = "type", unsigned = true, length = 2)
    @Default("0")
    @PropertyState(propertyName = "type")
    private Integer type;

    @Property(name = "country", length = 32)
    @Default("")
    @PropertyState(propertyName = "country")
    private String country;

    @Property(name = "province", length = 32)
    @PropertyState(propertyName = "province")
    private String province;

    @Property(name = "city", length = 32)
    @PropertyState(propertyName = "city")
    private String city;

    @Property(name = "location_addr", length = 200)
    @PropertyState(propertyName = "location_addr")
    private String locationAddr;

    @Property(name = "location_lon", length = 20)
    @Default("0")
    @PropertyState(propertyName = "location_lon")
    private Long locationLon;

    @Property(name = "location_lat", length = 20)
    @Default("0")
    @PropertyState(propertyName = "location_lat")
    private Long locationLat;

    @Property(name = "menu", length = 16383)
    @PropertyState(propertyName = "menu")
    private String menu;

    @Property(name = "summary", length = 16383)
    @PropertyState(propertyName = "summary")
    private String summary;

    @Property(name = "is_verified", unsigned = true, length = 1)
    @Default("0")
    @PropertyState(propertyName = "is_verified")
    private Integer isVerified;

    @Property(name = "is_deleted", unsigned = true, length = 1)
    @Default("0")
    @PropertyState(propertyName = "is_deleted")
    private Integer isDeleted;

    @Property(name = "is_msg_encrypted", unsigned = true, length = 1)
    @Default("0")
    @PropertyState(propertyName = "is_msg_encrypted")
    private Integer isMsgEncrypted;

    @Property(name = "mch_id", length = 32)
    @PropertyState(propertyName = "mch_id")
    private String mchId;

    @Property(name = "mch_key", length = 32)
    @PropertyState(propertyName = "mch_key")
    private String mchKey;

    @Property(name = "notify_url", length = 255)
    @PropertyState(propertyName = "notify_url")
    private String notifyUrl;

    @Property(name = "cert_file_path", length = 255)
    @PropertyState(propertyName = "cert_file_path")
    private String certFilePath;

    @Property(name = "status", unsigned = true, length = 2)
    @Default("0")
    @PropertyState(propertyName = "status")
    private Integer status;

    @Property(name = "site_id", nullable = false, length = 32)
    @PropertyState(propertyName = "site_id")
    private String siteId;

    @Property(name = "remark", length = 200)
    @PropertyState(propertyName = "remark")
    private String remark;

    @Property(name = "create_time", nullable = false, length = 13)
    @PropertyState(propertyName = "create_time")
    private Long createTime;

    @Property(name = "last_modify_time", length = 13)
    @Default("0")
    @PropertyState(propertyName = "last_modify_time")
    private Long lastModifyTime;

    /**
     * 构造器
     */
    public WechatAccount() {
    }

    /**
     * 构造器
     *
     * @param id
     * @param name
     * @param wechat
     * @param accountId
     * @param appId
     * @param appSecret
     * @param token
     * @param siteId
     * @param createTime
     */
    public WechatAccount(String id, String name, String wechat, String accountId, String appId, String appSecret, String token, String siteId, Long createTime) {
        this.id = id;
        this.name = name;
        this.wechat = wechat;
        this.accountId = accountId;
        this.appId = appId;
        this.appSecret = appSecret;
        this.token = token;
        this.siteId = siteId;
        this.createTime = createTime;
    }

    /**
     * 构造器
     *
     * @param id
     * @param name
     * @param wechat
     * @param accountId
     * @param appId
     * @param appSecret
     * @param appAesKey
     * @param lastAppAesKey
     * @param host
     * @param redirectUri
     * @param iconUrl
     * @param qrCode
     * @param token
     * @param type
     * @param country
     * @param province
     * @param city
     * @param locationAddr
     * @param locationLon
     * @param locationLat
     * @param menu
     * @param summary
     * @param isVerified
     * @param isDeleted
     * @param isMsgEncrypted
     * @param mchId
     * @param mchKey
     * @param notifyUrl
     * @param certFilePath
     * @param status
     * @param siteId
     * @param remark
     * @param createTime
     * @param lastModifyTime
     */
    public WechatAccount(String id, String name, String wechat, String accountId, String appId, String appSecret, String appAesKey, String lastAppAesKey, String host, String redirectUri, String iconUrl, String qrCode, String token, Integer type, String country, String province, String city, String locationAddr, Long locationLon, Long locationLat, String menu, String summary, Integer isVerified, Integer isDeleted, Integer isMsgEncrypted, String mchId, String mchKey, String notifyUrl, String certFilePath, Integer status, String siteId, String remark, Long createTime, Long lastModifyTime) {
        this.id = id;
        this.name = name;
        this.wechat = wechat;
        this.accountId = accountId;
        this.appId = appId;
        this.appSecret = appSecret;
        this.appAesKey = appAesKey;
        this.lastAppAesKey = lastAppAesKey;
        this.host = host;
        this.redirectUri = redirectUri;
        this.iconUrl = iconUrl;
        this.qrCode = qrCode;
        this.token = token;
        this.type = type;
        this.country = country;
        this.province = province;
        this.city = city;
        this.locationAddr = locationAddr;
        this.locationLon = locationLon;
        this.locationLat = locationLat;
        this.menu = menu;
        this.summary = summary;
        this.isVerified = isVerified;
        this.isDeleted = isDeleted;
        this.isMsgEncrypted = isMsgEncrypted;
        this.mchId = mchId;
        this.mchKey = mchKey;
        this.notifyUrl = notifyUrl;
        this.certFilePath = certFilePath;
        this.status = status;
        this.siteId = siteId;
        this.remark = remark;
        this.createTime = createTime;
        this.lastModifyTime = lastModifyTime;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }


    /**
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * @param name the name to set
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * @return the wechat
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * @param wechat the wechat to set
     */
    public void setWechat(String wechat) {
        this.wechat = wechat;
    }

    /**
     * @return the accountId
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * @param accountId the accountId to set
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    /**
     * @return the appId
     */
    public String getAppId() {
        return appId;
    }

    /**
     * @param appId the appId to set
     */
    public void setAppId(String appId) {
        this.appId = appId;
    }

    /**
     * @return the appSecret
     */
    public String getAppSecret() {
        return appSecret;
    }

    /**
     * @param appSecret the appSecret to set
     */
    public void setAppSecret(String appSecret) {
        this.appSecret = appSecret;
    }

    /**
     * @return the appAesKey
     */
    public String getAppAesKey() {
        return appAesKey;
    }

    /**
     * @param appAesKey the appAesKey to set
     */
    public void setAppAesKey(String appAesKey) {
        this.appAesKey = appAesKey;
    }

    /**
     * @return the lastAppAesKey
     */
    public String getLastAppAesKey() {
        return lastAppAesKey;
    }

    /**
     * @param lastAppAesKey the lastAppAesKey to set
     */
    public void setLastAppAesKey(String lastAppAesKey) {
        this.lastAppAesKey = lastAppAesKey;
    }

    /**
     * @return the host
     */
    public String getHost() {
        return host;
    }

    /**
     * @param host the host to set
     */
    public void setHost(String host) {
        this.host = host;
    }

    /**
     * @return the redirectUri
     */
    public String getRedirectUri() {
        return redirectUri;
    }

    /**
     * @param redirectUri the redirectUri to set
     */
    public void setRedirectUri(String redirectUri) {
        this.redirectUri = redirectUri;
    }

    /**
     * @return the iconUrl
     */
    public String getIconUrl() {
        return iconUrl;
    }

    /**
     * @param iconUrl the iconUrl to set
     */
    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl;
    }

    /**
     * @return the qrCode
     */
    public String getQrCode() {
        return qrCode;
    }

    /**
     * @param qrCode the qrCode to set
     */
    public void setQrCode(String qrCode) {
        this.qrCode = qrCode;
    }

    /**
     * @return the token
     */
    public String getToken() {
        return token;
    }

    /**
     * @param token the token to set
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * @return the type
     */
    public Integer getType() {
        return type;
    }

    /**
     * @param type the type to set
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * @return the country
     */
    public String getCountry() {
        return country;
    }

    /**
     * @param country the country to set
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * @return the province
     */
    public String getProvince() {
        return province;
    }

    /**
     * @param province the province to set
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * @return the city
     */
    public String getCity() {
        return city;
    }

    /**
     * @param city the city to set
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * @return the locationAddr
     */
    public String getLocationAddr() {
        return locationAddr;
    }

    /**
     * @param locationAddr the locationAddr to set
     */
    public void setLocationAddr(String locationAddr) {
        this.locationAddr = locationAddr;
    }

    /**
     * @return the locationLon
     */
    public Long getLocationLon() {
        return locationLon;
    }

    /**
     * @param locationLon the locationLon to set
     */
    public void setLocationLon(Long locationLon) {
        this.locationLon = locationLon;
    }

    /**
     * @return the locationLat
     */
    public Long getLocationLat() {
        return locationLat;
    }

    /**
     * @param locationLat the locationLat to set
     */
    public void setLocationLat(Long locationLat) {
        this.locationLat = locationLat;
    }

    /**
     * @return the menu
     */
    public String getMenu() {
        return menu;
    }

    /**
     * @param menu the menu to set
     */
    public void setMenu(String menu) {
        this.menu = menu;
    }

    /**
     * @return the summary
     */
    public String getSummary() {
        return summary;
    }

    /**
     * @param summary the summary to set
     */
    public void setSummary(String summary) {
        this.summary = summary;
    }

    /**
     * @return the isVerified
     */
    public Integer getIsVerified() {
        return isVerified;
    }

    /**
     * @param isVerified the isVerified to set
     */
    public void setIsVerified(Integer isVerified) {
        this.isVerified = isVerified;
    }

    /**
     * @return the isDeleted
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * @param isDeleted the isDeleted to set
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * @return the isMsgEncrypted
     */
    public Integer getIsMsgEncrypted() {
        return isMsgEncrypted;
    }

    /**
     * @param isMsgEncrypted the isMsgEncrypted to set
     */
    public void setIsMsgEncrypted(Integer isMsgEncrypted) {
        this.isMsgEncrypted = isMsgEncrypted;
    }

    /**
     * @return the mchId
     */
    public String getMchId() {
        return mchId;
    }

    /**
     * @param mchId the mchId to set
     */
    public void setMchId(String mchId) {
        this.mchId = mchId;
    }

    /**
     * @return the mchKey
     */
    public String getMchKey() {
        return mchKey;
    }

    /**
     * @param mchKey the mchKey to set
     */
    public void setMchKey(String mchKey) {
        this.mchKey = mchKey;
    }

    /**
     * @return the notifyUrl
     */
    public String getNotifyUrl() {
        return notifyUrl;
    }

    /**
     * @param notifyUrl the notifyUrl to set
     */
    public void setNotifyUrl(String notifyUrl) {
        this.notifyUrl = notifyUrl;
    }

    /**
     * @return the certFilePath
     */
    public String getCertFilePath() {
        return certFilePath;
    }

    /**
     * @param certFilePath the certFilePath to set
     */
    public void setCertFilePath(String certFilePath) {
        this.certFilePath = certFilePath;
    }

    /**
     * @return the status
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * @param status the status to set
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * @return the siteId
     */
    public String getSiteId() {
        return siteId;
    }

    /**
     * @param siteId the siteId to set
     */
    public void setSiteId(String siteId) {
        this.siteId = siteId;
    }

    /**
     * @return the remark
     */
    public String getRemark() {
        return remark;
    }

    /**
     * @param remark the remark to set
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * @return the createTime
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * @param createTime the createTime to set
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * @return the lastModifyTime
     */
    public Long getLastModifyTime() {
        return lastModifyTime;
    }

    /**
     * @param lastModifyTime the lastModifyTime to set
     */
    public void setLastModifyTime(Long lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }


    //
    // Chain
    //

    public static WechatAccountBuilder builder() {
        return new WechatAccountBuilder();
    }

    public WechatAccountBuilder bind() {
        return new WechatAccountBuilder(this);
    }

    public static class WechatAccountBuilder {

        private WechatAccount _model;

        public WechatAccountBuilder() {
            _model = new WechatAccount();
        }

        public WechatAccountBuilder(WechatAccount model) {
            _model = model;
        }

        public WechatAccount build() {
            return _model;
        }

        public String id() {
            return _model.getId();
        }

        public WechatAccountBuilder id(String id) {
            _model.setId(id);
            return this;
        }

        public String name() {
            return _model.getName();
        }

        public WechatAccountBuilder name(String name) {
            _model.setName(name);
            return this;
        }

        public String wechat() {
            return _model.getWechat();
        }

        public WechatAccountBuilder wechat(String wechat) {
            _model.setWechat(wechat);
            return this;
        }

        public String accountId() {
            return _model.getAccountId();
        }

        public WechatAccountBuilder accountId(String accountId) {
            _model.setAccountId(accountId);
            return this;
        }

        public String appId() {
            return _model.getAppId();
        }

        public WechatAccountBuilder appId(String appId) {
            _model.setAppId(appId);
            return this;
        }

        public String appSecret() {
            return _model.getAppSecret();
        }

        public WechatAccountBuilder appSecret(String appSecret) {
            _model.setAppSecret(appSecret);
            return this;
        }

        public String appAesKey() {
            return _model.getAppAesKey();
        }

        public WechatAccountBuilder appAesKey(String appAesKey) {
            _model.setAppAesKey(appAesKey);
            return this;
        }

        public String lastAppAesKey() {
            return _model.getLastAppAesKey();
        }

        public WechatAccountBuilder lastAppAesKey(String lastAppAesKey) {
            _model.setLastAppAesKey(lastAppAesKey);
            return this;
        }

        public String host() {
            return _model.getHost();
        }

        public WechatAccountBuilder host(String host) {
            _model.setHost(host);
            return this;
        }

        public String redirectUri() {
            return _model.getRedirectUri();
        }

        public WechatAccountBuilder redirectUri(String redirectUri) {
            _model.setRedirectUri(redirectUri);
            return this;
        }

        public String iconUrl() {
            return _model.getIconUrl();
        }

        public WechatAccountBuilder iconUrl(String iconUrl) {
            _model.setIconUrl(iconUrl);
            return this;
        }

        public String qrCode() {
            return _model.getQrCode();
        }

        public WechatAccountBuilder qrCode(String qrCode) {
            _model.setQrCode(qrCode);
            return this;
        }

        public String token() {
            return _model.getToken();
        }

        public WechatAccountBuilder token(String token) {
            _model.setToken(token);
            return this;
        }

        public Integer type() {
            return _model.getType();
        }

        public WechatAccountBuilder type(Integer type) {
            _model.setType(type);
            return this;
        }

        public String country() {
            return _model.getCountry();
        }

        public WechatAccountBuilder country(String country) {
            _model.setCountry(country);
            return this;
        }

        public String province() {
            return _model.getProvince();
        }

        public WechatAccountBuilder province(String province) {
            _model.setProvince(province);
            return this;
        }

        public String city() {
            return _model.getCity();
        }

        public WechatAccountBuilder city(String city) {
            _model.setCity(city);
            return this;
        }

        public String locationAddr() {
            return _model.getLocationAddr();
        }

        public WechatAccountBuilder locationAddr(String locationAddr) {
            _model.setLocationAddr(locationAddr);
            return this;
        }

        public Long locationLon() {
            return _model.getLocationLon();
        }

        public WechatAccountBuilder locationLon(Long locationLon) {
            _model.setLocationLon(locationLon);
            return this;
        }

        public Long locationLat() {
            return _model.getLocationLat();
        }

        public WechatAccountBuilder locationLat(Long locationLat) {
            _model.setLocationLat(locationLat);
            return this;
        }

        public String menu() {
            return _model.getMenu();
        }

        public WechatAccountBuilder menu(String menu) {
            _model.setMenu(menu);
            return this;
        }

        public String summary() {
            return _model.getSummary();
        }

        public WechatAccountBuilder summary(String summary) {
            _model.setSummary(summary);
            return this;
        }

        public Integer isVerified() {
            return _model.getIsVerified();
        }

        public WechatAccountBuilder isVerified(Integer isVerified) {
            _model.setIsVerified(isVerified);
            return this;
        }

        public Integer isDeleted() {
            return _model.getIsDeleted();
        }

        public WechatAccountBuilder isDeleted(Integer isDeleted) {
            _model.setIsDeleted(isDeleted);
            return this;
        }

        public Integer isMsgEncrypted() {
            return _model.getIsMsgEncrypted();
        }

        public WechatAccountBuilder isMsgEncrypted(Integer isMsgEncrypted) {
            _model.setIsMsgEncrypted(isMsgEncrypted);
            return this;
        }

        public String mchId() {
            return _model.getMchId();
        }

        public WechatAccountBuilder mchId(String mchId) {
            _model.setMchId(mchId);
            return this;
        }

        public String mchKey() {
            return _model.getMchKey();
        }

        public WechatAccountBuilder mchKey(String mchKey) {
            _model.setMchKey(mchKey);
            return this;
        }

        public String notifyUrl() {
            return _model.getNotifyUrl();
        }

        public WechatAccountBuilder notifyUrl(String notifyUrl) {
            _model.setNotifyUrl(notifyUrl);
            return this;
        }

        public String certFilePath() {
            return _model.getCertFilePath();
        }

        public WechatAccountBuilder certFilePath(String certFilePath) {
            _model.setCertFilePath(certFilePath);
            return this;
        }

        public Integer status() {
            return _model.getStatus();
        }

        public WechatAccountBuilder status(Integer status) {
            _model.setStatus(status);
            return this;
        }

        public String siteId() {
            return _model.getSiteId();
        }

        public WechatAccountBuilder siteId(String siteId) {
            _model.setSiteId(siteId);
            return this;
        }

        public String remark() {
            return _model.getRemark();
        }

        public WechatAccountBuilder remark(String remark) {
            _model.setRemark(remark);
            return this;
        }

        public Long createTime() {
            return _model.getCreateTime();
        }

        public WechatAccountBuilder createTime(Long createTime) {
            _model.setCreateTime(createTime);
            return this;
        }

        public Long lastModifyTime() {
            return _model.getLastModifyTime();
        }

        public WechatAccountBuilder lastModifyTime(Long lastModifyTime) {
            _model.setLastModifyTime(lastModifyTime);
            return this;
        }

    }

    /**
     * WechatAccount 字段常量表
     */
    public class FIELDS {
        public static final String ID = "id";
        public static final String NAME = "name";
        public static final String WECHAT = "wechat";
        public static final String ACCOUNT_ID = "account_id";
        public static final String APP_ID = "app_id";
        public static final String APP_SECRET = "app_secret";
        public static final String APP_AES_KEY = "app_aes_key";
        public static final String LAST_APP_AES_KEY = "last_app_aes_key";
        public static final String HOST = "host";
        public static final String REDIRECT_URI = "redirect_uri";
        public static final String ICON_URL = "icon_url";
        public static final String QR_CODE = "qr_code";
        public static final String TOKEN = "token";
        public static final String TYPE = "type";
        public static final String COUNTRY = "country";
        public static final String PROVINCE = "province";
        public static final String CITY = "city";
        public static final String LOCATION_ADDR = "location_addr";
        public static final String LOCATION_LON = "location_lon";
        public static final String LOCATION_LAT = "location_lat";
        public static final String MENU = "menu";
        public static final String SUMMARY = "summary";
        public static final String IS_VERIFIED = "is_verified";
        public static final String IS_DELETED = "is_deleted";
        public static final String IS_MSG_ENCRYPTED = "is_msg_encrypted";
        public static final String MCH_ID = "mch_id";
        public static final String MCH_KEY = "mch_key";
        public static final String NOTIFY_URL = "notify_url";
        public static final String CERT_FILE_PATH = "cert_file_path";
        public static final String STATUS = "status";
        public static final String SITE_ID = "site_id";
        public static final String REMARK = "remark";
        public static final String CREATE_TIME = "create_time";
        public static final String LAST_MODIFY_TIME = "last_modify_time";
    }

    public static final String TABLE_NAME = "wechat_account";

}
