package net.ymate.module.wechat.model;

import net.ymate.platform.core.beans.annotation.PropertyState;
import net.ymate.platform.persistence.annotation.Default;
import net.ymate.platform.persistence.annotation.Entity;
import net.ymate.platform.persistence.annotation.Id;
import net.ymate.platform.persistence.annotation.Property;
import net.ymate.platform.persistence.jdbc.support.BaseEntity;

/**
 * WechatMessage generated By EntityGenerator on 2016/07/15 下午 16:46:31
 *
 * @author YMP
 * @version 1.0
 */
@Entity("wechat_message")
public class WechatMessage extends BaseEntity<WechatMessage, String> {

    private static final long serialVersionUID = 1L;

    @Id
    @Property(name = "id", nullable = false, length = 32)
    @PropertyState(propertyName = "id")
    private String id;

    @Property(name = "from_uid", nullable = false, length = 32)
    @PropertyState(propertyName = "from_uid")
    private String fromUid;

    @Property(name = "to_uid", nullable = false, length = 32)
    @PropertyState(propertyName = "to_uid")
    private String toUid;

    @Property(name = "content", nullable = false, length = 4194303)
    @PropertyState(propertyName = "content")
    private String content;

    @Property(name = "is_star", unsigned = true, length = 1)
    @Default("0")
    @PropertyState(propertyName = "is_star")
    private Integer isStar;

    @Property(name = "is_replied", unsigned = true, length = 1)
    @Default("0")
    @PropertyState(propertyName = "is_replied")
    private Integer isReplied;

    @Property(name = "is_autoreply", unsigned = true, length = 1)
    @Default("0")
    @PropertyState(propertyName = "is_autoreply")
    private Integer isAutoreply;

    @Property(name = "is_read", unsigned = true, length = 1)
    @Default("0")
    @PropertyState(propertyName = "is_read")
    private Integer isRead;

    @Property(name = "is_deleted", unsigned = true, length = 1)
    @Default("0")
    @PropertyState(propertyName = "is_deleted")
    private Integer isDeleted;

    @Property(name = "create_time", nullable = false, length = 13)
    @PropertyState(propertyName = "create_time")
    private Long createTime;

    @Property(name = "create_by", length = 100)
    @PropertyState(propertyName = "create_by")
    private String createBy;

    @Property(name = "session_flag", length = 32)
    @PropertyState(propertyName = "session_flag")
    private String sessionFlag;

    @Property(name = "idx_status", unsigned = true, length = 2)
    @Default("0")
    @PropertyState(propertyName = "idx_status")
    private Integer idxStatus;

    @Property(name = "type", unsigned = true, length = 2)
    @Default("0")
    @PropertyState(propertyName = "type")
    private Integer type;

    @Property(name = "status", unsigned = true, length = 2)
    @Default("0")
    @PropertyState(propertyName = "status")
    private Integer status;

    @Property(name = "site_id", nullable = false, length = 32)
    @PropertyState(propertyName = "site_id")
    private String siteId;

    @Property(name = "remark", length = 200)
    @PropertyState(propertyName = "remark")
    private String remark;

    /**
     * 构造器
     */
    public WechatMessage() {
    }

    /**
     * 构造器
     *
     * @param id
     * @param fromUid
     * @param toUid
     * @param content
     * @param createTime
     * @param siteId
     */
    public WechatMessage(String id, String fromUid, String toUid, String content, Long createTime, String siteId) {
        this.id = id;
        this.fromUid = fromUid;
        this.toUid = toUid;
        this.content = content;
        this.createTime = createTime;
        this.siteId = siteId;
    }

    /**
     * 构造器
     *
     * @param id
     * @param fromUid
     * @param toUid
     * @param content
     * @param isStar
     * @param isReplied
     * @param isAutoreply
     * @param isRead
     * @param isDeleted
     * @param createTime
     * @param createBy
     * @param sessionFlag
     * @param idxStatus
     * @param type
     * @param status
     * @param siteId
     * @param remark
     */
    public WechatMessage(String id, String fromUid, String toUid, String content, Integer isStar, Integer isReplied, Integer isAutoreply, Integer isRead, Integer isDeleted, Long createTime, String createBy, String sessionFlag, Integer idxStatus, Integer type, Integer status, String siteId, String remark) {
        this.id = id;
        this.fromUid = fromUid;
        this.toUid = toUid;
        this.content = content;
        this.isStar = isStar;
        this.isReplied = isReplied;
        this.isAutoreply = isAutoreply;
        this.isRead = isRead;
        this.isDeleted = isDeleted;
        this.createTime = createTime;
        this.createBy = createBy;
        this.sessionFlag = sessionFlag;
        this.idxStatus = idxStatus;
        this.type = type;
        this.status = status;
        this.siteId = siteId;
        this.remark = remark;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }


    /**
     * @return the fromUid
     */
    public String getFromUid() {
        return fromUid;
    }

    /**
     * @param fromUid the fromUid to set
     */
    public void setFromUid(String fromUid) {
        this.fromUid = fromUid;
    }

    /**
     * @return the toUid
     */
    public String getToUid() {
        return toUid;
    }

    /**
     * @param toUid the toUid to set
     */
    public void setToUid(String toUid) {
        this.toUid = toUid;
    }

    /**
     * @return the content
     */
    public String getContent() {
        return content;
    }

    /**
     * @param content the content to set
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * @return the isStar
     */
    public Integer getIsStar() {
        return isStar;
    }

    /**
     * @param isStar the isStar to set
     */
    public void setIsStar(Integer isStar) {
        this.isStar = isStar;
    }

    /**
     * @return the isReplied
     */
    public Integer getIsReplied() {
        return isReplied;
    }

    /**
     * @param isReplied the isReplied to set
     */
    public void setIsReplied(Integer isReplied) {
        this.isReplied = isReplied;
    }

    /**
     * @return the isAutoreply
     */
    public Integer getIsAutoreply() {
        return isAutoreply;
    }

    /**
     * @param isAutoreply the isAutoreply to set
     */
    public void setIsAutoreply(Integer isAutoreply) {
        this.isAutoreply = isAutoreply;
    }

    /**
     * @return the isRead
     */
    public Integer getIsRead() {
        return isRead;
    }

    /**
     * @param isRead the isRead to set
     */
    public void setIsRead(Integer isRead) {
        this.isRead = isRead;
    }

    /**
     * @return the isDeleted
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * @param isDeleted the isDeleted to set
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * @return the createTime
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * @param createTime the createTime to set
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * @return the createBy
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * @param createBy the createBy to set
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * @return the sessionFlag
     */
    public String getSessionFlag() {
        return sessionFlag;
    }

    /**
     * @param sessionFlag the sessionFlag to set
     */
    public void setSessionFlag(String sessionFlag) {
        this.sessionFlag = sessionFlag;
    }

    /**
     * @return the idxStatus
     */
    public Integer getIdxStatus() {
        return idxStatus;
    }

    /**
     * @param idxStatus the idxStatus to set
     */
    public void setIdxStatus(Integer idxStatus) {
        this.idxStatus = idxStatus;
    }

    /**
     * @return the type
     */
    public Integer getType() {
        return type;
    }

    /**
     * @param type the type to set
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * @return the status
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * @param status the status to set
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * @return the siteId
     */
    public String getSiteId() {
        return siteId;
    }

    /**
     * @param siteId the siteId to set
     */
    public void setSiteId(String siteId) {
        this.siteId = siteId;
    }

    /**
     * @return the remark
     */
    public String getRemark() {
        return remark;
    }

    /**
     * @param remark the remark to set
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }


    //
    // Chain
    //

    public static WechatMessageBuilder builder() {
        return new WechatMessageBuilder();
    }

    public WechatMessageBuilder bind() {
        return new WechatMessageBuilder(this);
    }

    public static class WechatMessageBuilder {

        private WechatMessage _model;

        public WechatMessageBuilder() {
            _model = new WechatMessage();
        }

        public WechatMessageBuilder(WechatMessage model) {
            _model = model;
        }

        public WechatMessage build() {
            return _model;
        }

        public String id() {
            return _model.getId();
        }

        public WechatMessageBuilder id(String id) {
            _model.setId(id);
            return this;
        }

        public String fromUid() {
            return _model.getFromUid();
        }

        public WechatMessageBuilder fromUid(String fromUid) {
            _model.setFromUid(fromUid);
            return this;
        }

        public String toUid() {
            return _model.getToUid();
        }

        public WechatMessageBuilder toUid(String toUid) {
            _model.setToUid(toUid);
            return this;
        }

        public String content() {
            return _model.getContent();
        }

        public WechatMessageBuilder content(String content) {
            _model.setContent(content);
            return this;
        }

        public Integer isStar() {
            return _model.getIsStar();
        }

        public WechatMessageBuilder isStar(Integer isStar) {
            _model.setIsStar(isStar);
            return this;
        }

        public Integer isReplied() {
            return _model.getIsReplied();
        }

        public WechatMessageBuilder isReplied(Integer isReplied) {
            _model.setIsReplied(isReplied);
            return this;
        }

        public Integer isAutoreply() {
            return _model.getIsAutoreply();
        }

        public WechatMessageBuilder isAutoreply(Integer isAutoreply) {
            _model.setIsAutoreply(isAutoreply);
            return this;
        }

        public Integer isRead() {
            return _model.getIsRead();
        }

        public WechatMessageBuilder isRead(Integer isRead) {
            _model.setIsRead(isRead);
            return this;
        }

        public Integer isDeleted() {
            return _model.getIsDeleted();
        }

        public WechatMessageBuilder isDeleted(Integer isDeleted) {
            _model.setIsDeleted(isDeleted);
            return this;
        }

        public Long createTime() {
            return _model.getCreateTime();
        }

        public WechatMessageBuilder createTime(Long createTime) {
            _model.setCreateTime(createTime);
            return this;
        }

        public String createBy() {
            return _model.getCreateBy();
        }

        public WechatMessageBuilder createBy(String createBy) {
            _model.setCreateBy(createBy);
            return this;
        }

        public String sessionFlag() {
            return _model.getSessionFlag();
        }

        public WechatMessageBuilder sessionFlag(String sessionFlag) {
            _model.setSessionFlag(sessionFlag);
            return this;
        }

        public Integer idxStatus() {
            return _model.getIdxStatus();
        }

        public WechatMessageBuilder idxStatus(Integer idxStatus) {
            _model.setIdxStatus(idxStatus);
            return this;
        }

        public Integer type() {
            return _model.getType();
        }

        public WechatMessageBuilder type(Integer type) {
            _model.setType(type);
            return this;
        }

        public Integer status() {
            return _model.getStatus();
        }

        public WechatMessageBuilder status(Integer status) {
            _model.setStatus(status);
            return this;
        }

        public String siteId() {
            return _model.getSiteId();
        }

        public WechatMessageBuilder siteId(String siteId) {
            _model.setSiteId(siteId);
            return this;
        }

        public String remark() {
            return _model.getRemark();
        }

        public WechatMessageBuilder remark(String remark) {
            _model.setRemark(remark);
            return this;
        }

    }

    /**
     * WechatMessage 字段常量表
     */
    public class FIELDS {
        public static final String ID = "id";
        public static final String FROM_UID = "from_uid";
        public static final String TO_UID = "to_uid";
        public static final String CONTENT = "content";
        public static final String IS_STAR = "is_star";
        public static final String IS_REPLIED = "is_replied";
        public static final String IS_AUTOREPLY = "is_autoreply";
        public static final String IS_READ = "is_read";
        public static final String IS_DELETED = "is_deleted";
        public static final String CREATE_TIME = "create_time";
        public static final String CREATE_BY = "create_by";
        public static final String SESSION_FLAG = "session_flag";
        public static final String IDX_STATUS = "idx_status";
        public static final String TYPE = "type";
        public static final String STATUS = "status";
        public static final String SITE_ID = "site_id";
        public static final String REMARK = "remark";
    }

    public static final String TABLE_NAME = "wechat_message";

}
